### ISSUE TITLE
Web Support

### ISSUE THREAD

**Issue by markbreuss** [supabase-community/supabase-flutter#101]
Hello!

Im a bit confused about the different plattform support since there are two different versions out there.
Anyway I need Web & Windows support for my project and wanted to ask if both of them are supported?

Pub.Dev:
![image](https://user-images.githubusercontent.com/69714845/165314449-6dbcdc91-954e-4021-9ccc-d6e012e162dd.png)

Github Repo:
![image](https://user-images.githubusercontent.com/69714845/165314676-65ce26d0-1346-4904-b67f-77f23c5e115f.png)

Thanks!

**Comment by bdlukaa** [comment]
Yes, all of them is supported! Everywhere dart runs, supabase can run :)

The README will be updated. Thanks for reporting

**Comment by markbreuss** [comment]
Thanks for the prompt reply!
