### ISSUE TITLE
No keycloak provider

### ISSUE THREAD

**Issue by cremfert** [supabase-community/supabase-flutter#105]
Dear team,

I try to use this with my self-hosted keycloak. Unfortunately, the Provider class does not contain a value for Keycloak. How can I use this?

Thanks a lot!

**Comment by dshukertjr** [comment]
Hi @cremfert,

Are you trying to implement social login using keycloak? If so, is there a reason why you cannot use Supabase's social login?

**Comment by bdlukaa** [comment]
https://github.com/supabase-community/gotrue-dart/pull/74 should fix this!
