### ISSUE TITLE
Desktop support for provider auth

### ISSUE THREAD

**Issue by chimon2000** [supabase-community/supabase-flutter#106]
Currently this package is missing support for provider auth on desktop platforms.

It would be nice to have the ability to sign in to providers from MacOS, Windows, etc.

I believe there are two paths to achieve this:

- use the [uni_links_desktop](https://pub.dev/packages/uni_links_desktop) package
- migrate to the [applinks](https://pub.dev/packages/app_links) package that supports all platforms

**Comment by dshukertjr** [comment]
@chimon2000 Thanks for finding packages that will enable desktop support for OAuth login. 

It seems like uni_links is not maintained any more, so it might be good to move away from it. applinks looks promising! If you are interested and have the bandwidth for it, would you like to work on a PR to migrate to applinks?

**Comment by chimon2000** [comment]
Sure, I would love to take this on time willing.

**Comment by dshukertjr** [comment]
Closing this as this feature has landed!
