### ISSUE TITLE
can it be used in china？

### ISSUE THREAD

**Issue by paintingStyle** [supabase-community/supabase-flutter#107]
question:
I want to use this framework to develop Flutter App server side
can it be used in china？

**Comment by dshukertjr** [comment]
Hi @paintingStyle,

Thanks for your interest in Supabase. We cannot guarantee that the managed version of Supabase will work in China, but since Supabase is open sourced, you can always self host it on a server that works in China. 

You can read more about self hosting Supabase [here](https://supabase.com/docs/guides/hosting/overview).

**Comment by pluwen** [comment]
@paintingStyle 
I'm in China and I use Supabase for my hobby project, using Vercel as the backend service. The connection from Vercel to the Supabase database is smooth, and Vercel can also add your own domain name.

**Comment by paintingStyle** [comment]
supabase link --project-ref 


What are the parameters behind this command, I tried a lot and got an error






| |
Jay
|
|
***@***.***
|
签名由网易邮箱大师定制


On 05/10/2022 ***@***.***> wrote：

@paintingStyle
I'm in China and I use Supabase for my hobby project, using Vercel as the backend service. The connection from Vercel to the Supabase database is smooth, and Vercel can also add your own domain name.

**Comment by dshukertjr** [comment]
@paintingStyle Are you using the Supabase hosted version or self hosted version of Supabase?

If you are using the Supabase hosted version, you can pass your project reference to it like this:

```sh
supabase link --project-ref abcdefghijklmnopqrst
```

Project reference is the random string at the end of your supabase console's URL

You can read more about it [here](https://supabase.com/docs/reference/cli/supabase-link).
