### ISSUE TITLE
How generate right credentials for  Google Sign-in?

### ISSUE THREAD

**Issue by hmarat** [supabase-community/supabase-flutter#108]
In my flutter project which is for both Android and  iOS, I want to implement authentication with Google. Supabase wants from me the Client ID and Client secret. When I go to the Google Cloud Platform and try to generate an OAuth Client ID, it asks from me the project type(Web, Android, iOS).
1) What type should I select, if my project is for both Android and iOS, but Supabase asks from me only one Client ID and Client secret.
2) For example if I select Android, it gives me only Client ID, not client secret, but Supabase waits from me both.
3) Then I selected web application, and filled the client id and client secret fields in Supabase google sign in credentials. But when I try to sign in with `Provider.Google` in supabase, it in the same moment returns null data. 

p.s. Even consent screen is not opening

**Comment by hmarat** [comment]
@dshukertjr @phamhieu @bdlukaa

**Comment by bdlukaa** [comment]
https://github.com/supabase-community/gotrue-dart/pull/68#issuecomment-1117017649 may be related

**Comment by dshukertjr** [comment]
@hmarat At the moment, Supabase supports web based OAuth login. The PR @bdlukaa has mentioned is one that brings Supabase closer to adding a fully native OAuth login, but there are some works to be done so it will take a little more time for it to land. 

In the mean while, you mentioned that you are not able to sign in even using the web version. Are you using the [signInWithProvider()](https://supabase.com/docs/reference/dart/auth-signinwithprovider) method to sign in?

**Comment by hmarat** [comment]
@dshukertjr I didn't try web, I need only mobile for now :) So I can't use native google sign in with normal consent screen for now? When it will be implemented and available?

**Comment by dshukertjr** [comment]
@hmarat 

>I didn't try web, I need only mobile for now

Sorry, I wasn't clear enough. It does work on mobile app, but it will take users to the web version of the consent screen, which might not be ideal for some situations. Give `signInWithProvider()` a try and you will see it!

>So I can't use native google sign in with normal consent screen for now? When it will be implemented and available?

Hopefully not so far away from now, but we do not have a definite timeline on this.

**Comment by hmarat** [comment]
@dshukertjr okay, thanks :) What about getting access token on frontend and write some cloud function on Supabase?)And then send it from frontend to the supabase, and with just rest api, get all google user data for sign in?

**Comment by dshukertjr** [comment]
@hmarat If your goal is to obtain user's Google profile information and not sign users in via Google account, then I think that will work!

**Comment by hmarat** [comment]
My goal here is Sign in user with google. Can I get user's data with cloud function and just create new user or generate some token if user already exists?

**Comment by dshukertjr** [comment]
@hmarat If you are trying to sign users in via their Google account, then the method I provided [here](https://github.com/supabase-community/supabase-flutter/issues/108#issuecomment-1123723824) will be the best option, but have you tried it?

>Sorry, I wasn't clear enough. It does work on mobile app, but it will take users to the web version of the consent screen, which might not be ideal for some situations. Give signInWithProvider() a try and you will see it!

With the cloud functions route, you might be able to get user information, but you won't be able to sign the user in via our auth system unfortunately.

**Comment by hmarat** [comment]
Okay @dshukertjr , thanks. I will try it and let you know ;)

**Comment by hmarat** [comment]
@dshukertjr and if I do in the way you told, what is your suggestion about redirecting back to the app with already signed in user?😀

**Comment by dshukertjr** [comment]
@hmarat You can use [deeplinks](https://github.com/supabase-community/supabase-flutter#deeplink-config) to bring the users back to the app.

**Comment by avalanche-tm** [comment]
> @hmarat
> 
> > I didn't try web, I need only mobile for now
> 
> Sorry, I wasn't clear enough. It does work on mobile app, but it will take users to the web version of the consent screen, which might not be ideal for some situations. Give `signInWithProvider()` a try and you will see it!
> 
> > So I can't use native google sign in with normal consent screen for now? When it will be implemented and available?
> 
> Hopefully not so far away from now, but we do not have a definite timeline on this.

I'm getting a similar issue when trying to login with Google locally. Since only web version is working, I cannot enter my local android simulator address (http://10.0.2.2:54321/auth/v1/callback) as authorized redirect uri when creating Google web credentials in Google Cloud console. I get: 'Invalid Redirect: must end with a public top-level domain (such as .com or .org).'

How do I get around that? I'd like to do testing in my local supabase running in docker.

**Comment by hmarat** [comment]
> @hmarat You can use [deeplinks](https://github.com/supabase-community/supabase-flutter#deeplink-config) to bring the users back to the app.

I tried this, it can work, yes, but it's very uncomfortable, because asks from user open the link in app or continue with browser :(
Any other comfortable ways to do this?

**Comment by hmarat** [comment]
@dshukertjr If I will go firebase, will I be able to migrate all data into supabase in the upcoming future, if authentication will be fully implemented for mobile?

**Comment by dshukertjr** [comment]
>I tried this, it can work, yes, but it's very uncomfortable, because asks from user open the link in app or continue with browser :(
Any other comfortable ways to do this?

We are right around the corner at implementing native auth, which is what you are looking for it seems like!

>If I will go firebase, will I be able to migrate all data into supabase in the upcoming future, if authentication will be fully implemented for mobile?

Yup, we have Firebase to Supabase migration tool [here](https://github.com/supabase-community/firebase-to-supabase).

**Comment by hmarat** [comment]
@dshukertjr Amazing, thanks!

**Comment by dshukertjr** [comment]
@hmarat I will go ahead and close this issue. You can follow the progress on proper mobile auth flow [here](https://github.com/supabase-community/supabase-flutter/issues/5)!

**Comment by hmarat** [comment]
@dshukertjr any news? :)

**Comment by dshukertjr** [comment]
@hmarat Sorry, not quite yet. We will deliver the news once it has been implemented!

**Comment by hmarat** [comment]
@dshukertjr Okay, so what do you suggest ? :) I should release the app in july. 
1) Implement it with firebase and then later migrate to supabase.
2) Wait for native auth and implement it with supabase.
Thanks )

**Comment by dshukertjr** [comment]
@hmarat If I were you, I would just go with Supabase now and build the social login with the current implementation. Currently, you can still sign people in using Google account from your native app by redirecting the users to the browser only for signing in. You can follow the example [here](https://github.com/phamhieu/supabase-flutter-demo) on how you can do that. Eventually when true native sign in lands on Supabase, I would upgrade the supabase-flutter plugin to start using that. 

If you can release your app with just email + password auth to begin with, that might be a good option as well. 

If for some reason true native sign in is an absolute requirement, and you absolutely must release your app by July, then I would initially go with Firebase to play it safe.

**Comment by hmarat** [comment]
@dshukertjr Okay, thank you for the answer :) And lastly can you tell me the approximate time, when this will be ready ? :)

**Comment by dshukertjr** [comment]
@hmarat We are really hoping to get it shipped by August!

**Comment by hmarat** [comment]
> @hmarat We are really hoping to get it shipped by August!

Hey @dshukertjr :) We decided to wait  your  Auth implementation :) Do you think it will be done by August?

**Comment by dshukertjr** [comment]
Hey @hmarat,

We are working hard, but the auth team of Supabase have a lot on their plates, so cannot promise anything for sure. With that being said, native auth is a very demanded feature, so we would love to bring it ASAP. 

BTW, what is the auth provider that you plan to use? Maybe we can prioritize those ones.

**Comment by fabios9702** [comment]
I'm looking forward to this feature too, hoping to have this ASAP. I'm planning to use google and apple

**Comment by hmarat** [comment]
> Hey @hmarat,
> 
> 
> 
> We are working hard, but the auth team of Supabase have a lot on their plates, so cannot promise anything for sure. With that being said, native auth is a very demanded feature, so we would love to bring it ASAP. 
> 
> 
> 
> BTW, what is the auth provider that you plan to use? Maybe we can prioritize those ones. 

Google and Apple :) Thanks. Will be very happy to see it implemented :)

**Comment by hmarat** [comment]
@dshukertjr any news about the progress? :)

**Comment by dshukertjr** [comment]
There will be updates posted on this issue https://github.com/supabase-community/supabase-flutter/issues/5 when there is one.
