### ISSUE TITLE
Storage response not returning object id

### ISSUE THREAD

**Issue by avalanche-tm** [supabase-community/supabase-flutter#117]
When calling Supabase.instance.client.storage.upload() or uploadBinary() response returns string which is a path of uploaded file. How can I get id of the uploaded file from storage.objects table without making additional query?

**Comment by bdlukaa** [comment]
You already have the path of the file (`Supabase.instance.client.storage.upload(<path>)`). There isn't such thing as "file id", there is only the file path.

**Comment by avalanche-tm** [comment]
> You already have the path of the file (`Supabase.instance.client.storage.upload(<path>)`). There isn't such thing as "file id", there is only the file path.

There is id column in storage.objects table. Maybe I'm doing something wrong. I have items table and each item can have multiple images. I upload them to storage and I'd like to get their ids from storage.object table to create a link between item and images. Also I'm expecting deleting item will delete all the images.

**Comment by bdlukaa** [comment]
You can save the path to your database. You can get the download url by calling `Supabase.instance.client.storage.getSignedUrl(path)`

**Comment by avalanche-tm** [comment]
> You can save the path to your database. You can get the download url by calling `Supabase.instance.client.storage.getSignedUrl(path)`

Ok, but what is the purpose of the id column in storage.objects table then? I thought it was to reference images in other tables.

**Comment by dshukertjr** [comment]
@avalanche-tm 
I feel the confusion. `id` is just a primary key for the backend to use. As far as using Supabase, you wouldn't have to worry about the `id` column at all.
