### ISSUE TITLE
error G76A9B1F6: The method 'launchUrl' isn't defined for the class 'GoTrueClient'

### ISSUE THREAD

**Issue by iampopal** [supabase-community/supabase-flutter#118]
We are Getting 

error G76A9B1F6: The method 'launchUrl' isn't defined for the class 'GoTrueClient'

error when building our app 

the error comes from: 
supabase_auth.dart from line 170

Solotion: 
We have fixed this error by: 

Changing this line: 👇
    final result = await launchUrl(url, webOnlyWindowName: '_self');

to: 👇
    final result = await launch(url.toString(), webOnlyWindowName: '_self');

Please Fix the error by fixing this error on the repo so we can have clean builds on our server-side too

**Comment by dshukertjr** [comment]
@iampopal Sorry to hear that you are experiencing this error. For a temporal fix, could you delete your pubspec.lock file and rerun `flutter pub get`?

**Comment by iampopal** [comment]
did try this and still getting this error

**Comment by iampopal** [comment]
will be great if you use latest version of url_launcher package

**Comment by iampopal** [comment]
or remove the number of version from url_launcher so it will use url_launcher from the repo

**Comment by Vinzent03** [comment]
The min version of `url_launcher`[ is now](https://github.com/supabase-community/supabase-flutter/blob/main/pubspec.yaml) `^6.1.2`, which is after `^6.1.0`, where `launchUrl` got [introduced](https://pub.dev/packages/url_launcher/changelog#610). So all apps using this package will automatically resolve a version with `launchUrl` support.
