### ISSUE TITLE
Google OAuth does not allow WebViews

### ISSUE THREAD

**Issue by Shiba-Kar** [supabase-community/supabase-flutter#128]
![image](https://user-images.githubusercontent.com/24454722/173504097-2170e111-6dc0-445f-92f3-27c528fd522f.png)

Check this link [StackOverflow](https://stackoverflow.com/questions/43972730/getting-403-disallowed-user-agent-in-auth0-lock-for-android) google has blocked any WebViews to sucessfully pass  OAuth.

```dart
extension GoTrueClientSignInProvider on GoTrueClient {
  /// Signs the user in using a thrid parties providers.
  ///
  /// See also:
  ///
  ///   * <https://supabase.io/docs/guides/auth#third-party-logins>
  Future<bool> signInWithProvider(
    Provider provider, {
    AuthOptions? options,
  }) async {
    final res = await signIn(
      provider: provider,
      options: options,
    );
    final url = Uri.parse(res.url!);
    final result = await launchUrl(url,
        webOnlyWindowName: '_self', mode: LaunchMode.externalApplication); //Modified This
    return result;
  }
}
```
Doing the above code change ,I was able to get pass OAuth but now after authentication the chrome browser does not close automatically.

**Comment by dshukertjr** [comment]
@Shiba-Kar Thank you so much for reporting this. 

>Doing the above code change ,I was able to get pass OAuth but now after authentication the chrome browser does not close automatically.

Are you testing this on an iPhone?

**Comment by Shiba-Kar** [comment]
> @Shiba-Kar Thank you so much for reporting this.
> 
> > Doing the above code change ,I was able to get pass OAuth but now after authentication the chrome browser does not close automatically.
> 
> Are you testing this on an iPhone?

You can see from the image its an android emulator

**Comment by dshukertjr** [comment]
@Shiba-Kar Obviously I wasn't paying enough attention to details 😂

With the fix you proposed, you mentioned that chrome browser does not close automatically, but what happens instead? Did you setup [deeplinks](https://github.com/supabase-community/supabase-flutter#deeplink-config)?

**Comment by Shiba-Kar** [comment]
Yes I have done the deeplinks 
getting this once it launches in chrome 

![image](https://user-images.githubusercontent.com/24454722/173531051-4a5e45f0-b77c-4d7f-883b-8e698d13d227.png)

**Comment by dshukertjr** [comment]
@Shiba-Kar 
I can see that your the user was redirected to localhost. 

In order for the deeplinks to work, you need two things, you need two things, [set additional URL](https://supabase.com/docs/guides/with-flutter#setup-deep-links) in your supabase dashboard, and [call your login function with with `AuthOptions()`](https://supabase.com/docs/guides/with-flutter#setup-deep-links) where `redirectTo` is set to the URL set in your supabase dashboard as additional URL. 

Please try the above and see if fixes it!

**Comment by Shiba-Kar** [comment]
I have just changed the xml file in android and added all my Supabase details in ``` constants.dart ``` in this [Supabase Demo](https://github.com/phamhieu/supabase-flutter-demo.git)

**Comment by dshukertjr** [comment]
@Shiba-Kar 
>The OAuth works perfectly with supabase_flutter: ^0.2.10 not with supabase_flutter: ^0.3.1+2

Sounds like the configuration is fine then. Let me take a look!

**Comment by DanMossa** [comment]
This is unfortunately known and Supabase needs to support multiple clientIDs. There's another ticket on here where this is talked about

**Comment by Shiba-Kar** [comment]
#131 fixed it conformed !!
