### ISSUE TITLE
Subscription Does Not Return Old Record On Update Event

### ISSUE THREAD

**Issue by alig1882** [supabase-community/supabase-flutter#129]
I have a subscription to some table in the database for update events. The `newRecord` field in the payload is filled correctly with all the columns. However, the `oldRecord` field contains only one column, in my case the `id` column. I have also tested it when other columns in the row being updated are different, but the result is still the same.

The following is the output from adding another update callback on an already existing subscription,
```
{columns: [{name: id, type: varchar}, {name: num_swipes_remaining, type: int2}, {name: swipe_reset_time, type: timestamptz}, {name: profile_approved, type: bool}, {name: push_token, type: text}, {name: metric_units, type: bool}, {name: profile_reviewed, type: bool}, {name: test_user, type: bool}, {name: profile_active, type: bool}, {name: selfie_approved, type: bool}, {name: created_at, type: timestamptz}, {name: send_like_notifications, type: bool}, {name: blur_profile, type: bool}, {name: privacy_whitelist, type: _text}, {name: inactive_hide_messages, type: bool}], commit_timestamp: 2022-06-14T17:28:28Z, errors: null, old_record: {id: oTIT3DZgx8YPN1AyIFZ3AmVHOLK2}, record: {blur_profile: true, created_at: 2022-05-18T03:10:04.114796+00:00, id: oTIT3DZgx8YPN1AyIFZ3AmVHOLK2, inactive_hide_messages: false, metric_units: false, num_swipes_remaining: 10, privacy_whitelist: [], profile_active: true, profile_approved: false, profile_reviewed: true, push_token: eskT, selfie_approved: false, send_like_notifications: true, swipe_reset_time: null, test_user: true}, schema: public, table: swipe_parameters, type: UPDATE}
```

Let me know if there is any other information I can provide that would be helpful.

**Comment by dshukertjr** [comment]
Hi @alig1882,

I think this is related to this description in our [docs](https://supabase.com/docs/reference/dart/subscribe)

> If you want to receive the "previous" data for updates and deletes, you will need to set REPLICA IDENTITY to FULL, like this: ALTER TABLE your_table REPLICA IDENTITY FULL;

Let me know if running the above SQL fixes the problem!

**Comment by alig1882** [comment]
Yes! Completely missed that. Thank you very much for your quick response and incisive help <3
