### ISSUE TITLE
Supabase-Flutter vs Router/Navigator 2.0 (Beamer)

### ISSUE THREAD

**Issue by programmador** [supabase-community/supabase-flutter#134]
Is there any chance to use the lib with Router instead of Navigator?

I'm trying to do it the whole day and it seems like it's not possible.
Also it looks like #124 makes it possible.

Let's say my app consists of two main components.
* `App` ( `app.dart`) which creates `MaterialApp.router` via [Beamer](https://pub.dev/packages/beamer).
* `Page` (`my_page.dart`) - a Beamer page which is technically just a routed child of MaterialApp.

As I understand there's nothing wrong with Beamer and I could obtain same results with any other routing library.

So, here are two ways of how I tried to use supabase-flutter:

First:
Add SupabaseAuthState to `App`. No errors, auth is working. But I can do NOTHING after coming in the app via auth deep-link! Neither Navigator nor Router context exists as when the auth is done, the `App`'s build method is still not called. So no MaterialApp is created, no routing possible. I cannot redirect to any page, for example.

Second:
Add SupabaseAuthState to `Page`. First of all before redirecting to login page `missing token` error appears. Okay, this is not the most significant problem. The bad thing is happening after coming via a deep link. Debug log tells that auth is done (when Supabase.initialize is called in main.dart) but nothing happens then. App is stuck at URL localhost/#/access_token=blahblahblah showing `not found`. Because routing knows nothing about what the hell is `/access_token=blahblahblah`.

**Comment by programmador** [comment]
So here's how I've managed to handle such links.
The solution is Beamer specific. Also it's rather a hack than a solution.

So first of all: yes, AuthState is in `App` which calls `MaterialApp.router()` in state's `build()`.
So yes, You can't call any routes imperatively. We'll handle them declaratively instead.

Solution 1.
Quite a buggy one as it leaves that `localhost/#/access_token=blahblablah` in routing history. So You always see the token in URL when You push "back". Though it's only visible in web version, not mobile one.
```
class MenuLocation extends BeamLocation<BeamState> {
  MenuLocation({RouteInformation? routeInformation}) : super(routeInformation);

  @override
  List<Pattern> get pathPatterns => [
        '/',
        RegExp('/access_token*'),
      ];

  @override
  List<BeamPage> buildPages(BuildContext context, BeamState state) {
    return [
      // No conditions here. Both ways - with clear `/` and `/access_token=blah` You'll get just here.
      const BeamPage(
        key: ValueKey('game_selection'),
        title: 'Game Selection',
        child: GameSelectionPage(),
      ),
    ];
  }
}

```

Solution 2:
Actually it's the same solution but with intermediate page which could optionally clear the uri.

```
class AuthLocation extends BeamLocation<BeamState> {
  AuthLocation({RouteInformation? routeInformation}) : super(routeInformation);

  @override
  List<Pattern> get pathPatterns => [
        '/login',
        RegExp('/access_token*'),
      ];

  @override
  List<BeamPage> buildPages(BuildContext context, BeamState state) {

    return [
      if (state.uri.pathSegments.contains('login'))
        const BeamPage(
          key: ValueKey('login'),
          title: 'Login',
          child: LoginPage(),
        ),
      if (state.uri STARTS WITH "/access_token") {
        const BeamPage(
          child: A PAGE WHICH REDIRECTS SOMEWHERE ON LOAD
        )
      }
    ];
  }

```

**Comment by bdlukaa** [comment]
Since `SupabaseAuthState` was removed, I believe this issue is outdated and invalid. Closing this
