### ISSUE TITLE
Signup: Response is empty for EmailValidation 

### ISSUE THREAD

**Issue by vHanda** [supabase-community/supabase-flutter#144]
# Bug report

When using `signup(username, password)` the response object fetched has all its values as null. This is apparently supposed to indicate that the user now needs to validate the email. This is super cryptic, and took me some time to figure out.

## To Reproduce

```dart
var auth = Supabase.instance.client.auth;
var result = await auth.signUp(
    'test@gitjournal.io',
    'hellohello',
    options: AuthOptions(redirectTo: 'gitjournal-identity://callback'),
  );
  print(result);
  if (result.data != null) {
    print('result not null');
    print('done?');
  }
  print('data: ${result.data}');
  print('rawData: ${result.rawData}');
  print('user: ${result.user}');
  print('url: ${result.url}');
  print('provider: ${result.provider}');
  print('Error: ${result.error}');
  print('Error Message: ${result.error?.message}');
},
```

```
flutter: Instance of 'GotrueSessionResponse'
flutter: data: null
flutter: rawData: null
flutter: user: null
flutter: url: null
flutter: provider: null
flutter: Error: null
flutter: Error Message: null
```

## Expected behavior

Some easy way of figuring out that email validation is now required. One option would be to add a `bool emailValidationRequired` in the `GotrueSessionResponse`. Please let me know what solution would be acceptable.

I might / might-not provide a PR once the solution is agreed on. I don't want to commit myself.

**Comment by dshukertjr** [comment]
This has been resolved as indicated in the following issue. 

https://github.com/supabase/gotrue/issues/227
>If there's a valid date in the user object returned on the email_confirmed_at and/or phone_confirmed_at fields, then the user has confirmed their email and/or phone number.
