### ISSUE TITLE
Supabase auth navigator bug

### ISSUE THREAD

**Issue by nextdev1111** [supabase-community/supabase-flutter#145]
When I implemented supabase auth in my flutter app.

I saw some bugs. As the per the tutorial, changed  all the **state<>** to **authstate<>** but when I click on confim button in email sent for sign up. My screens just navigate 10 times to open my home screen. 

**I think its a authstate issue**

Please help

**Comment by bdlukaa** [comment]
Can you share any reproducible code?

**Comment by nextdev1111** [comment]
[https://github.com/nextdev1111/app_design_home_screen](https://github.com/nextdev1111/app_design_home_screen)

This is the code.

**Comment by nextdev1111** [comment]
When I continue with google 2 times, then at 3rd attempt, it loads my home_screen 5 to 10 times. It's too buggy.

**Comment by nextdev1111** [comment]
After giving it some time. I found that it's not navigator problem. The auth state increments on every time I logout and again login. In simple words : -

1. If I login, it will navigate to the auth screen
2. If I logout, it will navigate me 2 times to the auth screen.
3. If I again login, it will navigate me 3 times to the home screen.
4. If I again logout, it will navigate me 4 times to the auth screen.
5.This goes on like this. The most you login or logout, the more times it will navigate there.

**Comment by nextdev1111** [comment]
Hi there, it worked when I removed the authrequiredstate from the homescreen.

I think that authrequired screen was creating a mess.
