### ISSUE TITLE
[Proposal]Support for supabase raw queries

### ISSUE THREAD

**Issue by maheshmnj** [supabase-community/supabase-flutter#148]
Not sure if this feature is supported, I looked into the source code But I couldn't find a way to execute raw queries something like

```dart
final response = await _supabase.query('select * from $table1').execute();
```

Basically, I wanted to use joins, ~But I couldn't find that either~,
I found a way to use joins but looks like we don't need to specify a columnName on which the join is happening

```dart
  final response = await _supabase
        .from('$table1')
        .select('*, $table2!inner(*)')
        // .eq('$table2.$innerJoinColumn', '$table1.$innerJoinColumn')
        .execute();
```

 So I was hoping raw query would help me run any kind of SQL query.

**Comment by bdlukaa** [comment]
I believe raw query is not supported on the client libraries to avoid SQL injection. I don't think the js client library supports it either

**Comment by dshukertjr** [comment]
@maheshmnj
Supporting raw query introduces security problem, so most likely will never be supported. 

Currently, you can perform joins on tables that are associated via foreign keys, and when you have multiple foreign key relationships between two tables, an error message with instructions on how you can disambiguate will be thrown!
