### ISSUE TITLE
Multi threading

### ISSUE THREAD

**Issue by bdlukaa** [supabase-community/supabase-flutter#150]
We can not make use of supabase in another thread (we can, but not in a friendly way). Everytime a new thread is created, we'd need to reinitialize the supabase instance, which would be annoying and costly to do.

So, we should move heavy computation tasks, such as json encoding/decoding and networking requests to another thread. This would improve the overall app performance, unblocking the UI and resulting in better apps.

**Additional context**
- https://docs.flutter.dev/cookbook/networking/background-parsing
- https://blog.codemagic.io/understanding-flutter-isolates/

**Comment by Vinzent03** [comment]
I think this can be closed now, right? Adding isolates to postgrest should be enough, as the other package don't have huge json responses or requests.

**Comment by dshukertjr** [comment]
@Vinzent03 Yup, I think we can close this one!

**Comment by bdlukaa** [comment]
functions may also have huge payloads

**Comment by dshukertjr** [comment]
@bdlukaa 
Ah, true!
