### ISSUE TITLE
Perform `or` on foreign table

### ISSUE THREAD

**Issue by dshukertjr** [supabase-community/supabase-flutter#151]
In js, we can perform or on foreign table like this

```typescript
const { data, error } = await supabase
  .from('countries')
  .select('id, cities(*)')
  .or('name.eq.Wellington,name.eq.Paris', { foreignTable: "cities" })
```

We should add this to Dart library as well!

JS Docs: https://supabase.com/docs/reference/javascript/or#use-or-on-foreign-tables

**Comment by Vinzent03** [comment]
Hey @dshukertjr  I think already fixed this in https://github.com/supabase-community/postgrest-dart/pull/71 and is a duplicate of #121

**Comment by dshukertjr** [comment]
My bad 😂 
I thought I saw something like this some where 😂
