### ISSUE TITLE
Realtime with filters not working

### ISSUE THREAD

**Issue by imcouri** [supabase-community/supabase-flutter#152]
I'm using the latest version of flutter_supabase and supabase_dart, and as far as I've tested real-time only works if there are no filters applied and you're listening to changes in the entire table.

for example, this code works
```dart
Supabase.instance.client
        .from('messages')
        .on(SupabaseEventTypes.all, (payload)  async {
         //do something
}).subscribe();
```
but this doesn't 

```dart
Supabase.instance.client
        .from('messages:room_id=eq.$roomID')
        .on(SupabaseEventTypes.all, (payload)  async {
         //do something else
}).subscribe();

```

At this point, I'm not sure if it's an issue caused by the plugin or a Supabase itself since older versions of this app, released months ago, are having the same problem.

**Comment by imcouri** [comment]
hey @dshukertjr,
sorry for not updating this issue, i found out that it only happens when the search query contains ':'. Since all room ids include this character i am unable to receive real time updates. It could also be due to a server side/supabase issue as well since even older versions of the app are experiencing the same issue.

**Comment by dshukertjr** [comment]
@imcouri 
Can you provide an example id value that didn't work? I could not reproduce this issue with the following code:
```dart
Supabase.instance.client
    .from('random:content=eq.a.b')
    .on(SupabaseEventTypes.all, (payload) {
  print(payload);
}).subscribe();
```

BTW, It's interesting that your id column contains `.`. For id column, generally you cannot go wrong by using [UUID](https://supabase.com/docs/guides/database/extensions/uuid-ossp) type!

**Comment by imcouri** [comment]
@dshukertjr
I believe you've mistaken my previous response. All ids contain colons (:). However, the ID format is not up to me since the client specifically asked for this format since they will be integrating this new system into their old one, and that's how they do it in the old one.` support:luggage:2fbaNrjbQklvaESmOZHoS2` for example doesn't work. I've tried it in different projects, supabase versions and operating systems, but none of them detect when a change happens.

**Comment by dshukertjr** [comment]
@imcouri 
Oops, yup, I did 😂 

In that case, I see the problem. I will try to fix it and include it in the next package launch, which is next Monday!

**Comment by dshukertjr** [comment]
@imcouri Sorry, false alarm. 

Realtime does work with columns with `:` in it. I was able to get data with the following code. 

```dart
Supabase.instance.client
    .from('random:content=eq.support:luggage:2fbaNrjbQklvaESmOZHoS2')
    .on(SupabaseEventTypes.all, (payload) {
  print(payload);
}).subscribe();
```

Could you check if the same issue happens in another Suapbase instance? If it still persists, could you provide a whole set of minimal code to reproduce the issue?

**Comment by imcouri** [comment]
@dshukertjr 
It seems like it was a server-side issue after all, and it magically disappeared yesterday.
