### ISSUE TITLE
'Hide My Email' does not return the privacy relay email with 'Sign in with Apple'

### ISSUE THREAD

**Issue by tetsuya** [supabase-community/supabase-flutter#158]
# Bug report

## Describe the bug

The original email is shown even if a user has chosen to use 'Hide My Email'.

## Expected behaviour

`ramdom-string@privaterelay.appleid.com` is used.

## Screenshots

![Screen Shot 2022-07-31 at 11 03 47](https://user-images.githubusercontent.com/1000796/182009096-d7b6ffa8-accc-481d-83e6-5f495d75d179.jpg)

## System information

- Version of supabase_flutter: 0.3.3
- Version of Flutter: 2.10.5

**Comment by dshukertjr** [comment]
Hi @tetsuya, 
Do you have some code to reproduce this?

**Comment by tetsuya** [comment]
Hi @dshukertjr,

Sure. I just create a new project: https://github.com/tetsuya/hide_my_email

You should be able to reproduce the issue once you set `SUPABASE_URL` and `SUPABASE_ANON_KEY` in the `.env` file and set up OAuth credentials on your dashboard.

**Comment by dshukertjr** [comment]
@tetsuya 

Thanks for the repo. If it's okay, could I borrow your Supabase URL and anon key as well. 

We should not have access to the user's email address when users select `Hide my Email` at all, so the behavior is a bit odd.

**Comment by tetsuya** [comment]
@dshukertjr 

I've included app-specific info to the repo. Please let me know if you need any other info.

**Comment by dshukertjr** [comment]
@tetsuya 
Thank you for providing the Supabase credentials with me. 

I have tested it, and can confirm that my email address was hidden on the client side. I used `dshukertjr@gmail.com` apple account to sign in, but from your dashboard, do you see a user with email address `dshukertjr@gmail.com`? 

<img width="562" alt="Screen Shot 2022-08-03 at 14 53 58" src="https://user-images.githubusercontent.com/18113850/182543553-ca347ec0-b40b-4513-9a3a-49947b139603.png">

When using `Hide my Email` option, apple would not even give Supabase access to the original email address, so this should not be happening. Could you retry it by yourself to see that it is working properly?

**Comment by tetsuya** [comment]
@dshukertjr Thank you for looking into this, much appreciated. 

No, I don't see your original email address on my dashboard either.

I'm going to close the issue for now since the problem is not reproducible on your side. However, it shows the original email address for my apple account - even if I delete the user from Authentication or create a new project on Supabase and try it from scratch. I'll play around a bit more this weekend.

**Comment by tetsuya** [comment]
I've confirmed that I'm able to use 'Hide My Email' on my iPhone. There is a possibility that the beta version of iOS 16 (20A5312e) on a simulator may have the issue.

Thank you again for spending some time looking into this.
