### ISSUE TITLE
Login/Signup not working, the user is redirect always to localhost 

### ISSUE THREAD

**Issue by fabios9702** [supabase-community/supabase-flutter#161]
Hi, I didn't change my code, but starting from this morning the login with magic link/google and apple is not working anymore, I'm redirecting the user to 'io.supabase.flutterquickstart://login-callback/', but instead is redirect to localhost:300.

I've also added the URLs inside Auth settings.

Is there any problem with Auth?  

this is my code:

`supabase.auth.signInWithProvider(
        Provider.apple,
        options: AuthOptions(
            redirectTo: 'io.supabase.flutterquickstart://login-callback/'),
      );`

`supabase.auth.signInWithProvider(
        Provider.google,
        options: AuthOptions(
            redirectTo: 'io.supabase.flutterquickstart://login-callback/'),
      );`

**Comment by oluwaseye** [comment]
@fabios9702 have you updated your AndroidManifest.xml and Info.plist?

**Comment by fabios9702** [comment]
@oluwaseye 
Yes it was working, now it seems that the redirect link is always the one on supabase instead of the one that I pass in the AuthOptions, even If I've added the redirect URL to the supabase console it always redirect me to localhost:3000.

**Comment by dshukertjr** [comment]
@fabios9702 
Would you be able to provide a screenshot of your Auth settings page of your Supabase console?

**Comment by fabios9702** [comment]
@dshukertjr 

This is my Auth settings page

<img width="1157" alt="Schermata 2022-08-03 alle 16 17 41" src="https://user-images.githubusercontent.com/34335189/182631486-647ea28e-cf45-423e-b200-cce64fbdea9e.png">
<img width="1012" alt="Schermata 2022-08-03 alle 16 17 56" src="https://user-images.githubusercontent.com/34335189/182631511-2bef883e-1c3b-4c34-9306-9ead19348d39.png">

**Comment by dshukertjr** [comment]
@fabios9702 Thank you so much for providing the screenshot. I was able to reproduce this as well. Currently checking with the auth team to figure out the cause of this.

**Comment by dshukertjr** [comment]
@fabios9702 
So I created an issue in Gotrue repo to track this issue. If there is any updates to this issue, it will be posted on that issue. 
https://github.com/supabase/gotrue/issues/590

**Comment by Ashwaq3** [comment]
Facing same issue 😬

**Comment by J0** [comment]
Hey all, 

Auth team here -- sorry to hear that you are facing issues with the platform 😞  we're looking into the issue and will get back to you as soon as we can. In the mean time, please feel free to track progress in the issue that @dshukertjr has mentioned.

Thanks!

**Comment by J0** [comment]
Hey all, 

We've rolled out a patch which should resolve this issue -- going to close for now but feel free to re-open if you're still facing issues.


Thanks!

**Comment by fabios9702** [comment]
@J0 I'm still facing the issue

**Comment by Ashwaq3** [comment]
In my case it doesn’t redirect to the app but once i enter the app after the auth I find it authenticated..

**Comment by dshukertjr** [comment]
@fabios9702 If setting `redirectTo` is still not redirecting you to different URL, then please send `support@supabase.io` and email and share your project reference with it. Our Auth team will take a look at your project!

**Comment by J0** [comment]
Hey @fabios9702 and @Ashwaq3,

Sorry to hear that you're still facing issues. As @dshukertjr mentioned, do shoot over an email to support@supabase.io and we'll look at it as soon as we can!

Joel

**Comment by hf** [comment]
Hey everyone, we recently had a change in GoTrue that accidentally broke some redirect URLs. Since we've rolled it back. If you're still facing this issue please do let support@supabase.io know!

**Comment by innomatica** [comment]
Hi, I think I am still facing the same issue. 

I am following the steps in the [Quickstart](https://supabase.com/docs/guides/getting-started/tutorials/with-flutter). Regardless of the `emailRedirectTo` parameter

```
  Future<void> _signIn() async {
    setState(() {
      _isLoading = true;
    });
    try {
      await supabase.auth.signInWithOtp(
        email: _emailController.text,
        emailRedirectTo:
            kIsWeb ? null : 'io.supabase.flutterquickstart://login-callback/',
      );
```

The Magic Link email is generated with the `Site URL`, i.e. `http://localhost:3000`

Here is my URL Configuration

![Screenshot from 2022-12-22 13-42-00](https://user-images.githubusercontent.com/17297855/209204561-e72ebb2d-89b2-4a75-962a-f22580fadcf8.png)

Flutter SDK version: supabase_flutter 1.2.2
