### ISSUE TITLE
StorageFileApi type is not exposed

### ISSUE THREAD

**Issue by caseycrogers** [supabase-community/supabase-flutter#169]
I store references to different parts of my DB in a helper file to simplify access to them:
```dart
SupabaseQueryBuilder get profilesQuery => supabase.from('profiles');
.
.
.
```

However, if I try to do this for a storage bucket, it doesn't work:
```dart
StorageFileApi get profilePicturesBucket = supabase.storage.from('profile_pictures');
```
Compile error:
`Undefined class 'StorageFileApi'`

From what I can tell, the `StorageFileApi` type is not exposed anywhere by the SDK so I can't use it in things like a getter function.
It doesn't seem like there's a problem with simply assigning it to a variable without an explicit type:
```dart
final profilePicturesBucket = supabase.storage.from('profile_pictures');
```

So I'll simply do the above for now, but it'd be nice if the `StorageFileApi` type were exposed by the Dart sdk so that I could reference it in variable declarations and function signatures.

**Comment by dshukertjr** [comment]
@caseycrogers 
You are right! There was a bug where all the exported types within storage was not being exported properly, which was fixed in the most recent version of supabase_flutter, but I just noticed that `StorageFileApi` was never exported in the first place. Will do another release to fix this one.

**Comment by caseycrogers** [comment]
Awesome thanks!

**Comment by Vinzent03** [comment]
@caseycrogers Does it work now for you? If not, run `flutter pub upgrade supabase_flutter` and  `flutter pub upgrade storage_client`, because you need
- `supabase_flutter`: `1.0.0-dev.3`
- `storage_client`: `1.0.0-dev.3`

**Comment by caseycrogers** [comment]
Just updating `supabase_flutter` to dev.3 worked, thanks!
