### ISSUE TITLE
Session not stored with the latest supabase_flutter update

### ISSUE THREAD

**Issue by sumchans** [supabase-community/supabase-flutter#17]
supabase_flutter v 0.2.1

I curreny following the supabase flutter quickstart tutorial https://supabase.io/docs/guides/with-flutter.

Here is my link to the project - https://github.com/sumchans/Bol 

I haven't made any drastic changes to the tutorial, all I have worked on is the login_page.dart

The issue is -

1. A user signs up or signs in with phone.
2. The user closes and then reopens the app
3. The user is directed to the sign in screen.

Expected result - The user should be automatically signed in with the session information currently on device.

Testing this project on the iOS simulator.

Running this code print null for response.
```
    final response = await supabase.auth.signIn(phone: _phoneNumber);
    print(response.data);
```

**Comment by bdlukaa** [comment]
What happens if the user signs in with email? May be related to https://github.com/supabase/gotrue-dart/issues/29

**Comment by sumchans** [comment]
I tried using email sign at first which was close to two weeks ago. At the time email session was not working as well.

**Comment by dshukertjr** [comment]
@sumchans 
I just cloned your app and made a small modification to be able to sign in via email. The session was persisted!

The session not being persisted seems like it is because you are using phone auth and as @bdlukaa has pointed out, there is this issue currently that is preventing phone auth state to be persisted. 
https://github.com/supabase/gotrue-dart/issues/29

**Comment by sumchans** [comment]
Okay thanks Tyler. I thought with the latest supabase flutter update this would have been solved as well. Any idea how long we have to wait for this to get solved on the server side.

**Comment by dshukertjr** [comment]
@sumchans 
No idea when exactly the issue on the server side will get fixed, but maybe you can give a thumbs up on the issue https://github.com/supabase/gotrue/issues/141 to let the team know that you want that update!

**Comment by sumchans** [comment]
Just gave a thumbs up. It is so bad that we are not able to use phone authentication because of this issue.

**Comment by dshukertjr** [comment]
@sumchans Supabase team move super fast, so let's wait and see 😁

**Comment by sumchans** [comment]
Sounds good

**Comment by nstrelow** [comment]
Does this also affect provider logins such as GitLab?
Currently not working for me.

Will downgrade supabase_flutter, hope that fixes it.

**Comment by dshukertjr** [comment]
Hi @nstrelow!
It should not be affecting provider login. Did downgrading `supabase_flutter` fix the problem? If you have your code in a public repo, I can take a look.

**Comment by nstrelow** [comment]
The code is public, but the Readme instructions are not up-to-date (using melos for mono repo stuff).
https://github.com/hpi-studyu/studyu

I have some dependency issues, so I still need to fix that. It did not work, but I did not have the time to debug deeper. It worked without a problem on 0.0.8 or so.

Also I have a weird hive error, I might raise an issue at some point: Something about Hive.box not being opened?

I'll update here for more info at some point next week

**Comment by bdlukaa** [comment]
Closing as duplicated of https://github.com/supabase-community/gotrue-dart/issues/29 which may be fixed by https://github.com/supabase-community/gotrue-dart/pull/55
