### ISSUE TITLE
Opening Magic Link doesn't invoke onAuthStateChange

### ISSUE THREAD

**Issue by TyBarthel** [supabase-community/supabase-flutter#170]
I'm testing out 1.0.0-dev.3 for a MacOS desktop app.  I get asked from the browser to open the *.app, the application gets focused properly, but no callback is fired in onAuthStateChange.

**Comment by dshukertjr** [comment]
Thank you @TyBarthel for opening this issue. 

Is the repo that you are working on public? Any chance that I could take a look at it?

**Comment by TyBarthel** [comment]
Unfortunately it isn't, but I'll see about reproducing it with a small sandbox.

I did notice that I'm using the `auth` part of the `SupabaseClient` which is a type of `GoTrueClient`, whereas the new examples are using a type `SupabaseAuth`.  Is `supabase.client.auth.onAuthStateChange` deprecated possibly?

**Comment by TyBarthel** [comment]
I did confirm Magic Links work as expected with the `SupabaseAuth` type instead of using `supabase.client.auth`.  Seems like there's some room for some refactoring or cleanup between the two and maybe some documentation updates.

**Comment by bdlukaa** [comment]
Magic links only work on a Flutter environment, since Dart alone can not handle incoming unilinks.

> Is supabase.client.auth.onAuthStateChange deprecated possibly?

This is the part of the Dart SDK, where unilinks aren't available. @dshukertjr should we add to the stream when log in usign magic links?

**Comment by dshukertjr** [comment]
@bdlukaa 
Sorry if I'm missing something here, but wouldn't `supabase.client.auth.onAuthStateChange` and `SupabaseAuth. onAuthChange` fire at the same time? It seems so to me when I look at the code. 
https://github.com/supabase-community/supabase-flutter/blob/main/lib/src/supabase_auth.dart#L94

**Comment by MachariaK** [comment]
Make sure that you initialize SupabaseAuth and it will work.
