### ISSUE TITLE
Delete that violates RLS returns 200 but does not execute

### ISSUE THREAD

**Issue by caseycrogers** [supabase-community/supabase-flutter#175]
Context: RLS enabled and RLS rules that do not allow `delete`, version 1.0.0-dev.3 of `flutter_supabase`

Action: `await supbase.from('posts').delete().eq('id', post.id)`

Expected result: An exception thrown, with a 401 forbidden showing up in the API logs

Actual result: no exception thrown, empty data result returned, and a 200 showing up in the API logs

I'm not sure if the current behavior is intended or not (maybe it's a security thing to prevent data leaks??). I think it'd be great if either:
The behavior were updated to meet "expected result"
or
The current behavior were explicitly documented in the Dart docs for `delete`

**Comment by dshukertjr** [comment]
Thanks for opening this issue @caseycrogers!

As you have suspected this behavior is intended so that attacker would not be able to obtain existing rows with certain values. 

Documenting this behavior sounds like an amazing idea! I will add that to my task queue!

**Comment by caseycrogers** [comment]
Also, I wonder if there's a way to expose the error information server side in the API logs? That'd be a trusted environment where data leaks aren't a concern.

**Comment by caseycrogers** [comment]
I forgot about this weird behavior and wasted a lot of time wondering why a 200 DELETE was returning no rows and deleting no data. This really really should be exposed as an error or warning of some sort in the API logs at the very least.

**Comment by dshukertjr** [comment]
@caseycrogers Sorry that you had to spend some extra time because of this behavior. 

I would like to close this issue because the core issue is related to the Supabase platform itself, but please do feel free to [open a discussion](https://github.com/supabase/supabase/discussions) to let the team know of your feedback on adding this to the server side logs.
