### ISSUE TITLE
Add `upsert` method to storage

### ISSUE THREAD

**Issue by caseycrogers** [supabase-community/supabase-flutter#177]
I'd like to be able to "upsert" an object to storage so that I don't have to check if it already exists before uploading/updating it:
`supabase.storage.from('some-bucket-id').upsert(someFile, 'some/path');`
^ Will update the object if present, insert a new object otherwise

**Comment by bdlukaa** [comment]
There is already this possibility:

https://github.com/supabase-community/storage-dart/blob/8d1f0fb948accfed4b39d8f2044ce5418eda8ff9/example/main.dart#L19-L26

```dart
supabase.storage.from('some-bucket-id').upload(
  someFile, 'some/path',
  fileOptions: const FileOptions(upsert: true),
);
```

**Comment by caseycrogers** [comment]
Oh cool! thanks I'll try this. FWIW I'd love having an explicit upsert method that's just a wrapper on this as it's far more convenient/discoverable.

**Comment by caseycrogers** [comment]
> There is already this possibility:
> 
> https://github.com/supabase-community/storage-dart/blob/8d1f0fb948accfed4b39d8f2044ce5418eda8ff9/example/main.dart#L19-L26
> 
> ```dart
> supabase.storage.from('some-bucket-id').upload(
>   someFile, 'some/path',
>   fileOptions: const FileOptions(upsert: true),
> );
> ```

The above does not seem to be working:
Error:
```
StorageException(message: new row violates row-level security policy (USING expression) for table "objects", statusCode: 42501, 
```

Stacktrace:
```
#0      Fetch.Eval ()
#1      Fetch._handleResponse (package:storage_client/src/fetch.dart:150:7)
<asynchronous suspension>
#2      StorageFileApi.upload (package:storage_client/src/storage_file_api.dart:33:22)
<asynchronous suspension>
#3      CastDatabase.createCast (package:cast_me_app/business_logic/clients/cast_database.dart:42:5)
<asynchronous suspension>
#4      _PostPageViewState.build.<anonymous closure> (package:cast_me_app/pages/post_page_view.dart:64:17)
<asynchronous suspension>
#5      FutureExtensions.onError.<anonymous closure> (dart:async/future.dart:1013:15)
<asynchronous suspension>

```

**Comment by caseycrogers** [comment]
This doesn't work. I get this exception when using your above snippet to write a file that already exists, but not when writing a file that doesn't already exist:
`StorageException(message: new row violates row-level security policy (USING expression) for table "objects", statusCode: 42501, `
```
#0      Fetch.Eval ()
#1      Fetch._handleResponse (package:storage_client/src/fetch.dart:150:7)
<asynchronous suspension>
#2      StorageFileApi.upload (package:storage_client/src/storage_file_api.dart:33:22)
<asynchronous suspension>
#3      CastDatabase.createCast (package:cast_me_app/business_logic/clients/cast_database.dart:42:5)
<asynchronous suspension>
#4      _PostPageViewState.build.<anonymous closure> (package:cast_me_app/pages/post_page_view.dart:64:17)
<asynchronous suspension>
#5      FutureExtensions.onError.<anonymous closure> (dart:async/future.dart:1013:15)
<asynchronous suspension>
```

**Comment by Vinzent03** [comment]
What is your select policy? An upsert requires the select permission.

**Comment by caseycrogers** [comment]
My bucket is set to public and I have the following rule:
<img width="574" alt="image" src="https://user-images.githubusercontent.com/10675231/184225200-f81a1241-f606-4f0e-97f0-be37276ef038.png">

**Comment by dshukertjr** [comment]
@caseycrogers Shot in the dark, but the `-` in the bucket name might be the problem. Generally when you name things in Postgres, you want to use lower snake case or otherwise you would have to wrap those symbols with `""`. 

Try renaming the bucket to `some_bucket_id` and see if it works!

**Comment by rokk4** [comment]
@caseycrogers  Did you give your UPDATE Policy a USING and WITH CHECK clause? For me it needed both to work with upsert.

**Comment by caseycrogers** [comment]
@rokk4 adding a redundant policy with `using` fixed it, thanks!

@dshukertjr I didn't get around to testing underscores instead of hyphens. I initially tried using underscores when I named the bucket, but interestingly enough the Supabase storage UI doesn't let you include underscores when naming a new bucket.

**Comment by Vinzent03** [comment]
@caseycrogers I guess there is a reason behind disallowing `_` on storage buckets in the UI, but I don't know.
