### ISSUE TITLE
More filters on Realtime query

### ISSUE THREAD

**Issue by VittorioParagallo** [supabase-community/supabase-flutter#180]
I managed to test more filters (eq and or) in a realtime query, with a little hack to bypass the regex check on "eq".
The result of this experiment is that we can query and get a table with more then only 1 eq. 
On the other side the server will fire event also not matching the complex filter and when received on the client side this exception will be thrown because the sent record doesn't match the filters:
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Could not find the updated record.

With this little hack this is the resulting  PostgrestFilterBuilder query parameters after the eq chaining (it works even with or):
_query:
"select=%2A&region=eq.Campania&id_member=eq.FRRTRS92C58A024R"
_text:
"https://xxxxxx.supabase.co/rest/v1/members_registry?select=%2A&region=eq.Campania&id_member=eq.FRRTRS92C58A024R"

To replicate a similar behavior:
1)	I set the first eq in from (as by doc):
		
		Supabase.instance.client
			.from("members_registry:region=eq.Campania")
			.stream(['id_member'])
			.execute()
			.listen((event) {print(event);}

2)	Debug with a breakpoint in supabase_stream_builder at line 131.. right after it sets the query. 
	So when it stops at that breakpoint add through the debug console one more querylike:

			query = query.eq('id_member', 'FRRTRS92C58A024R');

 I saw in the source code of supabase/realtime: realtime/server/lib/realtime/subscribers_notification.ex and i see that the server at the moment can handle only 1 eq in realtime filters.

According to that i was able to have query with more filters, so the results are filtered while and the update events are not. 
So it receives the update also of not matching queries, but it can be discarded because it throws an exception.

 I was thinking that it is possible to change the source code of the streambuilder to allow more filters and ignore the [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Could not find the updated record. till it is developed in the realtime server?

So we can use complex queries in realtime without problems

**Comment by dshukertjr** [comment]
@VittorioParagallo 
Thank you for opening this issue.

If I understand you correctly, you are suggesting a new feature in `.stream()` method, where we support chaining multiple `.eq` filters with `&` or `or`, correct?

I don't know if we want to deviate the `.stream()` method too much from the currently available realtime API. There might be some updates on the realtime, and I don't want to make it hard to support those features when they land. 

As a workaround, you can certainly setup multiple [realtime subscriptions](https://supabase.com/docs/reference/dart/subscribe) and perform what you have described in this issue!

**Comment by VittorioParagallo** [comment]
Yes.. I was suggesting to use it in a way which could be using the eq method on stream like in non realtime queries for the select, and that would be nice because it would be a standard approch:

.from('members_registry')
.stream()
.eq('Region', 'Campania')
.eq('user_id', 'DFEIDJSN')

or, to keep things as they are, to allow a more complex query string in the from:
.from("members_registry:region=eq.Campania&user_id=DFEIDJSN")

But i get your point.
Thanks for replying
Vittorio

Sent from Mailspring ***@***.***/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrQU4zVUpTR1E3WU5UQzM2RVNCSUs2Q09CQU1JRlJFVkJOSEhFN0hZMkdZQHJlcGx5LmdpdGh1Yi5jb20%3D), the best free email app for work
On ago 12 2022, at 6:58 am, Tyler ***@***.***> wrote:
>
>
> @VittorioParagallo ***@***.***/1?redirect=https%3A%2F%2Fgithub.com%2FVittorioParagallo&recipient=cmVwbHkrQU4zVUpTR1E3WU5UQzM2RVNCSUs2Q09CQU1JRlJFVkJOSEhFN0hZMkdZQHJlcGx5LmdpdGh1Yi5jb20%3D)
> Thank you for opening this issue.
>
>
> If I understand you correctly, you are suggesting a new feature in .stream() method, where we support chaining multiple .eq filters with & or or, correct?
> I don't know if we want to deviate the .stream() method too much from the currently available realtime API. There might be some updates on the realtime, and I don't want to make it hard to support those features when they land.
> As a workaround, you can certainly setup multiple realtime subscriptions ***@***.***/2?redirect=https%3A%2F%2Fsupabase.com%2Fdocs%2Freference%2Fdart%2Fsubscribe&recipient=cmVwbHkrQU4zVUpTR1E3WU5UQzM2RVNCSUs2Q09CQU1JRlJFVkJOSEhFN0hZMkdZQHJlcGx5LmdpdGh1Yi5jb20%3D) and perform what you have described in this issue!
> —
> Reply to this email directly, view it on GitHub ***@***.***/3?redirect=https%3A%2F%2Fgithub.com%2Fsupabase-community%2Fsupabase-flutter%2Fissues%2F180%23issuecomment-1212729958&recipient=cmVwbHkrQU4zVUpTR1E3WU5UQzM2RVNCSUs2Q09CQU1JRlJFVkJOSEhFN0hZMkdZQHJlcGx5LmdpdGh1Yi5jb20%3D), or unsubscribe ***@***.***/4?redirect=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAN3UJSETPBSZX5LGNAGG4UTVYXKVRANCNFSM56HZ4WJQ&recipient=cmVwbHkrQU4zVUpTR1E3WU5UQzM2RVNCSUs2Q09CQU1JRlJFVkJOSEhFN0hZMkdZQHJlcGx5LmdpdGh1Yi5jb20%3D).
> You are receiving this because you were mentioned.
>


-- 
------------------------


Indirizzo istituzionale di posta elettronica 
degli studenti e dei laureati dell'Università di TorinoOfficial University 
of Turin email address for students and graduates

**Comment by dshukertjr** [comment]
Closing this for now, but please feel free to open any issues if you have any more suggesttions/ questions about anything!
