### ISSUE TITLE
Separate the HiveLocalStorage implementation into another package

### ISSUE THREAD

**Issue by leynier** [supabase-community/supabase-flutter#183]
Flutter has many alternatives for local databases, in cases where the developer doesn't want to use Hive, they will have to Hive dependency unnecessarily. I think we should separate the HiveLocalStorage implementation into another package and use EmptyLocalStorage by default.

The community can then contribute with different custom local storage implementations using different local database alternatives.

**Comment by dshukertjr** [comment]
Thanks for the suggestion @leynier!

I like the direction, but I would like to keep auth persistence on by default, because that is often times the intuitive behavior for auth provider. If you could come up with a way to keep auth persistence by default and remove Hive, I am happy to consider it!

**Comment by leynier** [comment]
Thanks for the quick response. What do you think about using [shared_preferences](https://pub.dev/packages/shared_preferences)?

Pros:
- Maintained by the Flutter team
- Focused on storing smaller data

Cons:
- Encryption is not supported
- Write operations with slower performance (but considering that write operations are not frequently, is not a big cons)

**Comment by dshukertjr** [comment]
@leynier 
We had some security concerns with SharedPreferences, so we went with Hive. Its light weight and gets the job done!

If people want to use something else for local storage, they can certainly do that and I think Hive is light enough to be ignored in that case.

**Comment by leynier** [comment]
I got it, so I will close the issue. Thanks for your time @dshukertjr and for the great work maintaining the Dart/Flutter ecosystem of Supabase.

PS: For learning purposes only. What security concerns do you have with SharedPreferences?

**Comment by dshukertjr** [comment]
@leynier 
Sorry for the late reply here. 

I think the main concern was that information stored on shared preferences are not encrypted at rest.

**Comment by leynier** [comment]
@dshukertjr there is no problem with the delay in the answers, thank you very much for taking the time to do it, I appreciate it.

A note about the encryption of the current implementation with Hive is that we only have the Box encryption activated if `encryptionKey` is not `null`, but in the initialization by default `encryptionKey` is always `null`. Is that the expected behavior?

https://github.com/supabase-community/supabase-flutter/blob/f20fb8bbd7b03f0ff00ca3691fc7cadc9f29eb3e/lib/src/local_storage.dart#L81

https://github.com/supabase-community/supabase-flutter/blob/f20fb8bbd7b03f0ff00ca3691fc7cadc9f29eb3e/lib/src/local_storage.dart#L85

https://github.com/supabase-community/supabase-flutter/blob/f20fb8bbd7b03f0ff00ca3691fc7cadc9f29eb3e/lib/src/supabase.dart#L65

**Comment by dshukertjr** [comment]
@bdlukaa would you be able to chime in here?

**Comment by bdlukaa** [comment]
`encryptionKey` is a property that must be set by the developer, since it's a unique key:

```dart
```

I wonder why that's not documentated. I'll open a documentation PR about it!

Related:
* https://docs.hivedb.dev/#/advanced/encrypted_box

**Comment by leynier** [comment]
Oh, it's a static property.  I hadn't noticed that detail. Thank you very much for your time guys.
