### ISSUE TITLE
Transform snake_case to camelCase

### ISSUE THREAD

**Issue by avalanche-tm** [supabase-community/supabase-flutter#185]
Is this feature already implemented in Flutter https://github.com/supabase/supabase/discussions/7136 ?

**Comment by dshukertjr** [comment]
Hi @avalanche-tm,

I don't know if transforming snake case to camel case should be a part of Supabase library. In Flutter, you can easily transform the properties from snake case to camel case like [this](https://github.com/supabase-community/flutter-chat/blob/main/lib/models/message.dart#L25), but would this not be enough? Let me know if you have any specific use case that you would want this feature!

**Comment by christianfl** [comment]
Talking about Flutter, it is even easier than that:

You need:

- json_serializable
- build_runner
- json_annotation

```
import 'package:json_annotation/json_annotation.dart';

part 'my_data_type.g.dart';

@JsonSerializable(
  includeIfNull: false, // Optional
  fieldRename: FieldRename.snake,
)
class MyDataType {
  MyDataType({
    String? id,
    int? numberOfSomething,
  });

  /// Connect the generated fromJson function to the `fromJson` factory.
  factory MyDataType.fromJson(Map<String, dynamic> json) =>
      _$MyDataTypeFromJson(json);

  /// Connect the generated toJson function to the `toJson` method.
  @override
  Map<String, dynamic> toJson() => _$MyDataTypeToJson(this);
}

```

run `flutter pub run build_runner build`, this generates the types automatically.

**Comment by avalanche-tm** [comment]
@christianfl that looks very promising, will try out. Thanks!
