### ISSUE TITLE
INSERT return null res

### ISSUE THREAD

**Issue by raphache** [supabase-community/supabase-flutter#189]
dependencies:
supabase_flutter: ^1.0.0-dev.4

Exemple:
final res = await supabase
  .from('cities')
  .insert([
    {'name': 'The Shire', 'country_id': 554}
  ])

"res" return NULL, and not full record.

**Comment by Vinzent03** [comment]
You need to append `.select()` to the query.

**Comment by raphache** [comment]
> You need to append `.select()` to the query.

perfect! thanks.
