### ISSUE TITLE
Cannot filter in anyway

### ISSUE THREAD

**Issue by vietlinhtspt** [supabase-community/supabase-flutter#196]
I am using filter to query data in some ways: 

column: table name ex: 'title'.
value: List of String: ['title'].

1. 
```dart
await Supabase.instance.client
        .from(table)
        .select()
        .contains(column, value);
```

2. 
```dart
await Supabase.instance.client
        .from(table)
        .select()
        .filter(column, 'cs', value);
```

It always throw an error: Unhandled Exception: PostgrestException(message: operator does not exist: text @> unknown, code: 42883, details: Not Found, hint: No operator matches the given name and argument types. You might need to add explicit type casts.)

Can anyone help me?

**Comment by dshukertjr** [comment]
@vietlinhtspt I would like to close this issue because as @Vinzent03 has suggested, the `.in_()` filter is the way to go here. Please feel free to open another issue if you are still experiencing some issues!
