### ISSUE TITLE
Reducing non dart or flutter official packages from Supabase

### ISSUE THREAD

**Issue by anggoran** [supabase-community/supabase-flutter#198]
### Current behavior
- There are a set of regular methods (File) that support Mobile and Desktop, and a set of binary methods (Uint8List) to support Web.
- Supabase storage-dart package uses universal_io.
- The one that should decide to choose which file picker package they are going to use are package users not maintainers.

### New behavior
- Replace universal_io with dart:io, since binary methods already cover the web platform with Uint8List type.

**Comment by dshukertjr** [comment]
I would like to close this issue for now, but please feel free to reopen it if you think it is appropriate!
