### ISSUE TITLE
execute() Method is deprecated, why?

### ISSUE THREAD

**Issue by carmas123** [supabase-community/supabase-flutter#200]
Using the v1.0.0-dev.4 version the lint inform that the `execute` method is deprecated and now we need to use `async/await` or `then`.
Please can you explain the correct method to use database with this version?

**Comment by Vinzent03** [comment]
You can just omit the `.execute()` method. Best to read the changelogs. For example of [postgrest](https://github.com/supabase-community/postgrest-dart/blob/master/CHANGELOG.md)

**Comment by carmas123** [comment]
Ok ok, thank you so much.
