### ISSUE TITLE
Insert returns null whereas documents says it should return the inserted row

### ISSUE THREAD

**Issue by Hamza-Imran75** [supabase-community/supabase-flutter#204]
**Describe the bug**
supabase_flutter: 1.0.0-dev.4 
Whenever I insert a row, I get a null return even though the document says it should return the inserted row by default.

**To Reproduce**
Do a simple insert and check its returned value.
` ref.read(supabaseClientProvider).from('feedback').insert({
      'feedback': feedback,
      'category_id': categoryId,
      'userid': user.roleNo
    }).then((res) {
      print(res);
    }, onError: (e) {
      print(e);
    });`

**Expected behavior**
Return the inserted row.

**Comment by bdlukaa** [comment]
This seems to be fixed by https://github.com/supabase-community/postgrest-dart/pull/88

You need to add `.select()` to the end of your query to get the inserted row!

**Comment by Hamza-Imran75** [comment]
Thanks, the documentation said by default so I assumed it was supposed to return without using select.
