### ISSUE TITLE
Not able to signin users but can register users

### ISSUE THREAD

**Issue by ak19992017** [supabase-community/supabase-flutter#208]
**Describe the bug**
I am able to Register users but shows error on trying to login with the same regisered user. 
I can confirm the registered users from the Supabase dashboard .
On SignIn it throws error -> GoTrueException(message: Invalid login credentials, statusCode: 400)
I am running the Flutter web app on Chrome .
I am using the supabase_flutter: 1.0.0-dev.4 plugin version.
Email confirmation turned off
Added redirect url shown in Supabase starter guide
Below is video demo

https://user-images.githubusercontent.com/71957886/188299857-cc2ec27c-e609-4229-9076-95afddb9a831.mp4

**To Reproduce**
You can refer the repo https://github.com/ak19992017/supa-auth
or codemagic page https://supa-auth.codemagic.app
**Expected behavior**
Successful signin if the user is successfully registered

**Debug console VScode**
Restarted application in 218ms.
***** Supabase init completed Instance of 'Supabase'
Got object store box in database supabase_authentication.
***** SupabaseDeepLinkingMixin startAuthObserver
***** SupabaseAuthState handleDeeplink http://localhost:57564/#/signin
onReceivedAuthDeeplink uri: http://localhost:57564/#/signin

**Additional context**
**Flutter doctor**
$ flutter doctor -v
[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.19044.1826], locale en-IN)
    • Flutter version 3.3.0 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (5 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0    
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\KIIT\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)   
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.70.2)
    • VS Code at C:\Users\KIIT\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.48.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 105.0.5195.54
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 104.0.1293.70

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by farshid-shokrolahi** [comment]
Facing the same issue. What did you do to solve it?
