### ISSUE TITLE
onReceivedAuthDeeplink custom function?

### ISSUE THREAD

**Issue by kilterskjalg** [supabase-community/supabase-flutter#211]
Hi guys. 

Thanks for the great work!

**Is your feature request related to a problem? Please describe.**
A user enters my android/ios app via a password reset link that has expired or been invalidated. My code does not detect this and the user experience is the same as a "regular opening" of the app (i.e. tap the app icon not a link). Problem: User gets confused.

**Describe the solution you'd like**
 A way of detecting that the app was opened from a link - in order to display a nice info message to my user if necessary.

**Describe alternatives you've considered**
Redo all from scratch.

**Additional context**
I can see messages in the debug log - including one that says: "Email link is invalid or has expired". If I only could show this to my user. 

My  ```pubspec.lock``` says ```supabase_flutter: 1.0.0-dev.4```

**Comment by dshukertjr** [comment]
Hi @kilterskjalg,

Thank you so much for opening this issue. I agree, there should be a way to detect and handle this error. Let me look into it a bit and get back to you!

**Comment by dshukertjr** [comment]
@kilterskjalg 

Actually, could you try the following? `SupabaseAuth.instance.initialSession` is not a well documented property yet, but is a variable that returns the initial session, and will throw if there were any errors while getting the initial session!

```dart
try {
  await SupabaseAuth.instance.initialSession;
} catch (error) {
  // handle error here
}
```

**Comment by kilterskjalg** [comment]
Thanks!
I guess I was hoping for a listener of sorts that would let me register a callback, analog to ```onAuthStateChange```.
I'll play around with your suggestion and see if it does the trick. 👍

**Comment by kilterskjalg** [comment]
Hmm, seems to me the ``ìnitialSession``` is ```null``` when (cold) starting the app with invalid link, and no error is thrown? Same as when starting app without prior log in. With prior log in I get an instance of ```Session```.

**Comment by dshukertjr** [comment]
That is a nice suggestion! Let me see if we can implement something nice like that!
