### ISSUE TITLE
Error into realtime _isTargetRecord method

### ISSUE THREAD

**Issue by ISIGest** [supabase-community/supabase-flutter#215]
This method handle realtime Update and Delete events checking `payload['eventType']` the problem is that this key is not present into payload but should be `payload['type']`

```
  bool _isTargetRecord({
    required Map<String, dynamic> record,
    required Map<String, dynamic> payload,
  }) {
    late final Map<String, dynamic> targetRecord;
    if (payload['eventType'] == 'UPDATE') {    <--- THE PROBLEM IS THERE
      targetRecord = payload['new']!;
    } else if (payload['eventType'] == 'DELETE') {     <--- AND THERE
      targetRecord = payload['old']!;
    }
    return _uniqueColumns
        .every((column) => record[column] == targetRecord[column]);
  }
```

Regards

**Comment by dshukertjr** [comment]
Thank you for reporting this! Fixing this ASAP!

**Comment by dshukertjr** [comment]
@ISIGest 
I did some digging, and actually, `eventType` seems correct in this case. 

You can see where it's creating the payload [here](https://github.com/supabase-community/realtime-dart/blob/main/lib/src/realtime_channel.dart#L581), which matches the behavior on js SDK as well as seen [here](https://github.com/supabase/realtime-js/blob/rc/src/RealtimeChannel.ts#L481).

Is your realtime not working properly? If so, there might be other causes.

**Comment by dshukertjr** [comment]
Okay, I do see a different issue that is preventing from update to work. Fixing it now!

**Comment by dshukertjr** [comment]
I believe the issue of not being able to listen to update or delete events has been resolved with the latest supabase-dart package. Releasing the supabase-flutter package now.

**Comment by carmas123** [comment]
> I believe the issue of not being able to listen to update or delete events has been resolved with the latest supabase-dart package. Releasing the supabase-flutter package now.

Sorry but this problem occurs from the 1.0.0-dev.6

**Comment by dshukertjr** [comment]
@carmas123 Does it occur on supabase-dart 1.0.0-dev.6 or supabase-flutter 1.0.0-dev.6?

**Comment by carmas123** [comment]
> @carmas123 Does it occur on supabase-dart 1.0.0-dev.6 or supabase-flutter 1.0.0-dev.6?

supabase_flutter

**Comment by dshukertjr** [comment]
@carmas123 
Okay, sorry for making you wait, but there is a new version of supabase-flutter coming soon [here](https://github.com/supabase-community/supabase-flutter/pull/217). This should fix this issue!

**Comment by dshukertjr** [comment]
@carmas123 @ISIGest With supabase-flutter 1.0.0-dev.7 that was just released right now, this issue should be fixed hopefully!

**Comment by carmas123** [comment]
> @carmas123 @ISIGest With supabase-flutter 1.0.0-dev.7 that was just released right now, this issue should be fixed hopefully!

Thank you so much I'll try it right away

**Comment by carmas123** [comment]
I got always this error:
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/6574219/190382305-427d1cf6-f9a4-484a-a11a-61b9cdfa0beb.png">

**Comment by Vinzent03** [comment]
@carmas123 May you place a breakpoint at that failing line and share your payload here?

**Comment by carmas123** [comment]
this is my payload:

```
{
   "columns":[
      {
         "name":"id",
         "type":"uuid"
      },
      {
         "name":"created_at",
         "type":"timestamptz"
      },
      {
         "name":"updated_at",
         "type":"timestamptz"
      },
      {
         "name":"user_id",
         "type":"uuid"
      },
      {
         "name":"sheet_id",
         "type":"uuid"
      }
   ],
   "commit_timestamp":"2022-09-15T15:21:43Z",
   "errors":null,
   "old_record":{
      "id":"d8917e47-b233-402c-a376-143a2ba39f4a"
   },
   "record":{
      "created_at":"2022-09-13T07:04:45.770049+00:00",
      "id":"d8917e47-b233-402c-a376-143a2ba39f4a",
      "sheet_id":"3029a825-59df-4575-a906-e979f595af8b",
      "updated_at":"2022-09-15T15:21:42.997981+00:00",
      "user_id":"0e215e82-179b-4fd5-833c-819cd7c80e92"
   },
   "schema":"public",
   "table":"sheet_links",
   "type":"UPDATE"
}
```

**Comment by Vinzent03** [comment]
@dshukertjr Why is the playload different from the test? May he use some old realtime version. Like is walrus different?

**Comment by dshukertjr** [comment]
@Vinzent03 Thanks for pinpointing the issue! Yeah, that seems like the issue here, doesn't it? 

@carmas123 @ISIGest  Sorry for this issue to happen. I will work on a fix for this right now.

**Comment by dshukertjr** [comment]
@carmas123 @carmas123 Also if you don't mind, could you share your project reference so I can ask the realtime team why the payload is coming in with the old format?

**Comment by carmas123** [comment]
> @carmas123 @carmas123 Also if you don't mind, could you share your project reference so I can ask the realtime team why the payload is coming in with the old format?

This project is self hosted.

**Comment by dshukertjr** [comment]
@carmas123 Ah, I see!

A fix is on the way on realtime-dart, but it might take a few days for us to update supabase-flutter. Sorry for the inconvenience.

**Comment by dshukertjr** [comment]
@ISIGest @carmas123 This should now be fixed with the latest supabase-flutter!

**Comment by carmas123** [comment]
> @ISIGest @carmas123 This should now be fixed with the latest supabase-flutter!

@dshukertjr now I got another error:

```
Tried calling: []("schema")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      RealtimeChannel._getEnrichedPayload
package:realtime_client/src/realtime_channel.dart:609
#2      RealtimeChannel.trigger
package:realtime_client/src/realtime_channel.dart:545
#3      RealtimeClient.onConnMessage.<anonymous closure>.<anonymous closure>
package:realtime_client/src/realtime_client.dart:294
#4      Iterable.forEach (dart:core/iterable.dart:325:35)
#5      RealtimeClient.onConnMessage.<anonymous closure>
package:realtime_client/src/realtime_client.dart:294
#6      new RealtimeClient.<anonymous closure>
package:realtime_client/src/realtime_client.dart:100
#7      RealtimeClient.onConnMessage
package:realtime_client/src/realtime_client.dart:277
#8      RealtimeClient.connect.<anonymous closure> (package:realtime_client/src/realti<…>
```


This is the method:

 ```
 Map<String, dynamic> _getEnrichedPayload(dynamic payload) {
    final postgresChanges = payload['data'];
    final schema = postgresChanges['schema'];
    final table = postgresChanges['table'];
    final commitTimestamp = postgresChanges['commit_timestamp'];
    final type = postgresChanges['type'];
    final errors = postgresChanges['errors'];

    final enrichedPayload = {
      'schema': schema,
      'table': table,
      'commit_timestamp': commitTimestamp,
      'eventType': type,
      'new': {},
      'old': {},
      'errors': errors,
    };

    return {
      ...enrichedPayload,
      ..._getPayloadRecords(postgresChanges),
    };
  }
```

this is the payload

<img width="410" alt="image" src="https://user-images.githubusercontent.com/6574219/190973559-6961e6e8-1381-445d-8b82-dc3695a4ff01.png">

**Comment by dshukertjr** [comment]
@carmas123 
Thanks for the details. BTW, you might know this, but you can use the 0.x versions of supabase-flutter to avoid this bug from happening.

**Comment by dshukertjr** [comment]
@carmas123 
Also, could you let me know what the version of your realtime docker compose is?

**Comment by carmas123** [comment]
> @carmas123 Also, could you let me know what the version of your realtime docker compose is?

v0.22.4

**Comment by dshukertjr** [comment]
Sorry for the delay here. A fix is on the way, this time with proper tests, and it should land on supabase-flutter within the next few days.
