### ISSUE TITLE
1.0.0-dev.8: presence failling?

### ISSUE THREAD

**Issue by cgestes** [supabase-community/supabase-flutter#222]
using a local supabase. (started this morning). under macos.

(postgres realtime is working with this supabase client, so I suspect the code managing channels is somehow working)

```dart
class PresenceRepository {
  late final String uid;

  void init(String uid) {
    this.uid = uid;
  }

  void registerPresence(String id) {
    final client = Supabase.instance.client;

    final chan = client.channel(id);
    chan.subscribe((status, [err]) async {
      print('Presence status: ${id} : ${status} - ${err}');
      if (status == 'SUBSCRIBED') {
        final status2 = await chan.track({uid: uid});
        print('presence: ${id} : ${status2}');
      }
    });
  }

  Stream<List<String>> subscribeToPresence(String id) {
    final controller = StreamController<List<String>>();
    final client = Supabase.instance.client;

    final chan = client.channel(id);
    chan.on(RealtimeListenTypes.presence, ChannelFilter(event: '*'), (a, [b]) {
      print(
          "currently online users: ${id} : ${a} - ${b} - ${chan.presenceState()}");
      // controller.add(somethingtofigureout);
    });
    return controller.stream;
  }

  void unregisterPresence(String id) {
    final client = Supabase.instance.client;
    print("Presence: unregister: ${id}");
    final chan = client.channel(id);
    chan.unsubscribe();
  }
}
```

(I register then subscribe once)

I get the following output:
```
flutter: Presence status: 42 : SUBSCRIBED - null
flutter: Presence status: 42 : CHANNEL_ERROR - {}
flutter: presence: 42 : ChannelResponse.timedOut
flutter: Presence status: 42 : SUBSCRIBED - null
flutter: Presence status: 42 : CHANNEL_ERROR - {}
flutter: presence: 42 : ChannelResponse.timedOut
... (repeats every seconds or so)
```

Is there something I am missing? (can it be some missing headers also? like it was for rpc in https://github.com/supabase-community/supabase-flutter/issues/221?)

**Comment by dshukertjr** [comment]
I can confirm this happens on local version of Supabase, but does not seem to happen with the cloud version of Supabase, which makes me think it might be a backend issue. If you could open an issue on [realtime](https://github.com/supabase/realtime) repo to confirm with them, it would be awesome!

**Comment by dshukertjr** [comment]
Closing this is with the comments from our realtime team.

https://github.com/supabase/realtime/issues/284#issuecomment-1224908325
>supabase/realtime docker image is not yet compatible with @supabase/realtime-js rc versions. We've been developing the new Broadcast and Presence in a private repo and will be moving over all code to this repo in the upcoming weeks
