### ISSUE TITLE
Supabase-Dart subscription only gets CLOSED event.

### ISSUE THREAD

**Issue by caturprasatya** [supabase-community/supabase-flutter#227]
**Describe the bug**
When using supabase realtime, after successfully subscribing. Suddenly realtime supabase closed and could not receive update events.  Have tried to rejoin supabase realtime it turns out that it is still closed too.

**Screenshots**
<img src="https://i.ibb.co/rZ9jHQ5/Screenshot-from-2022-09-28-08-58-24.png" alt="Screenshot-from-2022-09-28-08-58-24" border="0">

**Smartphone**
 - Version 9

**Comment by dshukertjr** [comment]
There was a bug that got fixed with the most recent version of supabase_flutter. Can you try using [v1.0.0-dev.9](https://pub.dev/packages/supabase_flutter/versions/1.0.0-dev.9).

**Comment by caturprasatya** [comment]
@dshukertjr after switching to that version, why can't I do the chaining method to .on()
<img src="https://i.ibb.co/k6dh6zX/Screenshot-from-2022-09-28-09-59-06.jpg" alt="Screenshot-from-2022-09-28-09-59-06" border="0">

**Comment by dshukertjr** [comment]
@caturprasatya Can you copy and paste your code?

Also, you can find the docs here for the new realtime API
https://supabase.com/docs/reference/dart/next/subscribe

**Comment by caturprasatya** [comment]
@dshukertjr oh this is my fault, I'm still using function .from()  before .on(). thank you very much, sir

**Comment by dshukertjr** [comment]
@caturprasatya Glad to be able to help! I will close this issue assuming with the latest version you are no longer facing the issue, but if you still are, please feel free to reopen it at any time!
