### ISSUE TITLE
Async/await does not return PostgrestResponse when querying.

### ISSUE THREAD

**Issue by MuhammedKpln** [supabase-community/supabase-flutter#228]
```.execute()``` is deprecated, while it's better to write less code but when using async/await instead which is the new standart, but it does not return PostgrestResponse. How do we catch errors, row counts and so on..

**Expected behavior**
It should return PostgrestResponse as a response.

**Screenshots**

**Smartphone (please complete the following information):**
 - Version [1.0.0-dev.9]

**Comment by Vinzent03** [comment]
You need to use try/catch now for exception handling. See the [postgrest changelog](https://github.com/supabase-community/postgrest-dart/blob/master/CHANGELOG.md#100-dev1)

**Comment by MuhammedKpln** [comment]
> You need to use try/catch now for exception handling. See the [postgrest changelog](https://github.com/supabase-community/postgrest-dart/blob/master/CHANGELOG.md#100-dev1)

Alright but what about count, statusCode and so on. Is there any plan to bring it back?

**Comment by Vinzent03** [comment]
How you obtain the count is listed in the changelog as well. Just specify the count method and the return type countains a `count` and `data` field. I think you get the status code when you set `forceResponse` to true in `FetchOptions`.

**Comment by MuhammedKpln** [comment]
Something feels wrong here, is this normal behavior? Well you can assign custom type instead of ```var``` but shouldn't it return PostgrestResponse by default?


with execute function

![Skärmbild 2022-10-05 123657](https://user-images.githubusercontent.com/17166855/194042185-efcac1ec-89dd-4fda-933a-a9b369e2e62d.png)


Without.
![Skärmbild 2022-10-05 123332](https://user-images.githubusercontent.com/17166855/194042194-b7074aed-a7d3-4eb6-b6da-771ffb964876.png)

**Comment by Vinzent03** [comment]
The return type is now dynamic. It depends on the options you specify like `.single()` or count options. For `forceResponse` and count options you get a `PostrestResponse`.
 Otherwise the data directly like `List` or `Map`.
