### ISSUE TITLE
Broadcast and presence support similar to realtime-js

### ISSUE THREAD

**Issue by aarjan** [supabase-community/supabase-flutter#230]
Any timeline when the broadcast and presence support will be available in dart/flutter like in realtime-js?

https://supabase.com/docs/guides/realtime
https://supabase.com/docs/guides/realtime/broadcast

**Comment by Vinzent03** [comment]
It's already available in the dev 1.x.x release. See this  [pr](https://github.com/supabase-community/realtime-dart/pull/47).

**Comment by dshukertjr** [comment]
@aarjan 
Yeah, sorry. We didn't announce it big, but supabase-flutter already has broadcast and presence. We don't have much documentations of it (yet), but you can find a sample code [here](https://pub.dev/packages/supabase_flutter/versions/1.0.0-dev.9/changelog#100-dev6) in the changelog!

**Comment by gauravmehta13** [comment]
Hi @dshukertjr , Is there any guide to use this for showing user status as  online/offline, This is a great feature and would be really helpful if we can have a similar guide for this.

**Comment by dshukertjr** [comment]
Hi @gauravmehta13 
Yeah, sorry for not having much tutorial material on these presence and broadcast feature. Our docs is going through an update right now, so would add these once the update is complete!
