### ISSUE TITLE
Update code example on readme for supabase-flutter

### ISSUE THREAD

**Issue by dshukertjr** [supabase-community/supabase-flutter#242]
**Is your feature request related to a problem? Please describe.**
The code example on supabase-flutter is still using the 0.X ones. 

**Describe the solution you'd like**
It should be using v1.X code sample.

**Comment by Vinzent03** [comment]
We definitely need to update the readme as fast as possible as well.

**Comment by dshukertjr** [comment]
Done here
https://github.com/supabase-community/supabase-flutter/pull/247
