### ISSUE TITLE
[FEAT] Limit to last missing

### ISSUE THREAD

**Issue by PcolBP** [supabase-community/supabase-flutter#243]
**Is your feature request related to a problem? Please describe.**
When trying to limit records to newest messages we're getting limit oldest ones. 

**Describe the solution you'd like**
Missing limitToLast query as it is in firebase.
```dart
if (limitToLast != null) {
    query = query.limitToLast(limitToLast);
  }
```

**Describe alternatives you've considered**
No alternatives?

**Additional context**
-

**Comment by Vinzent03** [comment]
I don't think postgres supports something like `limitToLast`, but I guess you are ordering your rows, so you can reverse the order and use normal limit.

**Comment by dshukertjr** [comment]
@PcolBP You can combine `.limit()` with `.order()` to get the newest or oldest records, so would like to close this issue. Feel free to open another issue if anything is unclear in the future!

```dart
// Gets the 10 newest rows
final data = await supabase.from('my_table').select().order('created_at', ascending: false).limit(10);

// Gets the 10 oldest rows
final data = await supabase.from('my_table').select().order('created_at', ascending: true).limit(10);
```
