### ISSUE TITLE
Issues with redirect url in v1.0.0

### ISSUE THREAD

**Issue by devon2018** [supabase-community/supabase-flutter#244]
**Describe the bug**
It seems that the latest version of this lib does not use the emailRedirectTo parameter correctly when using the `signInWithOtp` method, when looking at the `gotrue_client.dart` file it seems that you arent using the parameter if it gets passed.

**To Reproduce**
1. Install the supabase_flutter lib
2. Login using the signInWithOtp method passing a custom emailRedirectTo parameter
3. check email link, redirect parameter is not as expected.

**Expected behavior**
Should be using the emailRedirectTo parameter

**Screenshots**
<img width="587" alt="Screenshot 2022-10-20 at 11 17 40" src="https://user-images.githubusercontent.com/46196252/196922710-7c1c7d2f-53d0-4239-949a-4a510561aaf6.png">

**Smartphone (please complete the following information):**
 - Version Iphone14 plus simulator with ios 16

**Additional context**

**Comment by dshukertjr** [comment]
Found another bug in the SDK that prevents this feature from working.
