### ISSUE TITLE
const { data, error } = await supabase.auth.verifyOtp({ email, token, type: 'signup'})

### ISSUE THREAD

**Issue by inaxium** [supabase-community/supabase-flutter#248]
I try since yesterday following workflow:

1) resetPasswordForEmail
2) user get mail with   {{.Token}} => To change your password, enter your email and token, and the new password.
The token is valid for XX Miniutes. After that you have to get a new one.

Your Token : 745796

3) Call verifyOtp former UpdateUser

4) User is logged in and change his password. 

In ES it seem like this` verifyOtp({ "x@y.com", "745796", type: 'signup'})`

in Flutter the API Signature is Completely different:

```
  Future<void> signInWithOtp({
    String? email,
    String? phone,
    String? emailRedirectTo,
    bool? shouldCreateUser,
    Map<String, dynamic>? data,
    String? captchaToken,
  })
```
another one is a url what given in send password recovery <= I don't want to use it.

https://ozqqgkuoavbrfdkgzvfj.supabase.co/auth/v1/verify?token=e8b6c81c4fb9f24d3225b5c03471b48010323ad9cfa0fce5fafbc778&type=recovery&redirect_to=http://localhost:58265/

what comes from {{.ConfirmationURL}} 

What kind of token is this. Not JWT.

I'm in a new Project with supabase with Flutter I'm willing to write some Article to make all the Authentication stuff clear for other people. 

But first of all I've to understand it by myself.

But nevertheless I didn't try it in ES

[](https://github.com/supabase/supabase/discussions/4837)

**Comment by inaxium** [comment]
I try it in ES.
It Works.
    const {data, error} = await supabase.auth.verifyOtp({ email: email, token:token, type:"recovery" });

**Comment by inaxium** [comment]
![2022-10-23 20_03_49-inkgym – C__Users_frank_AppData_Local_Pub_Cache_hosted_pub dartlang org_gotrue-1](https://user-images.githubusercontent.com/51343921/197410886-6a380fe1-044e-43e2-a8e1-834f1b8b0623.png)

**Comment by leynier** [comment]
This issue is solved in https://github.com/supabase-community/gotrue-dart/commit/e44378564fd56ac7828fb161d40897d184b70bf1 and will be available after the merge of this pr https://github.com/supabase-community/gotrue-dart/pull/97

**Comment by inaxium** [comment]
OK

**Comment by inaxium** [comment]
OK

**Comment by dshukertjr** [comment]
@inaxium Just released a new version of gotrue-dart. You should be able to use it by deleting your pubspec.lock file in your Flutter application and re-running pub get!

**Comment by inaxium** [comment]
It works.

**Comment by dshukertjr** [comment]
I would like to close this issue, but please feel free to open another issue if anything is not working!
