### ISSUE TITLE
Forget password UI

### ISSUE THREAD

**Issue by iampopal** [supabase-community/supabase-flutter#25]
# Forget password web UI
Currently, forget password sends a reset email but not has a firebase like a web UI to enter a new password and conform it. 

After the user click on the reset password link in the email, 
we shall direct to a site where the user can enter a new password.

**Comment by dshukertjr** [comment]
Hi @iampopal!

You can make your own password reset page within your Flutter app to have the user reset their passwords!

**Comment by phamhieu** [comment]
> we shall direct to a site where the user can enter a new password.

on the redirect url for password reset, the type should be `type=recovery`. You can check for that param and show a reset password UI.

**Comment by iampopal** [comment]
Thank you @dshukertjr and @phamhieu 
May I see a simple app of the flutter native app on how to forget user passwords?

**Comment by iampopal** [comment]
I am using supabase for a windows desktop app as a backend, I think it will be great if supabase have a web UI for forget password by default.

**Comment by Vinzent03** [comment]
I think the dev should control the routing, but you can use the new [flutter-auth-ui](https://github.com/supabase-community/flutter-auth-ui) package.

**Comment by iampopal** [comment]
As we have 
Windows 
Mac
Android and iOS Users 

We have created a website page from there user forget thier password 

This is what worked well and easy for us

**Comment by iampopal** [comment]
If supabase team create and lunch a website simple for each project 
Like Firebase do 
It will make best developer experience and no publishing of a web page

**Comment by dshukertjr** [comment]
@iampopal 
Thanks for the suggestion!

Hosted auth pages provided by Supabase have been discussed internally, and although we cannot provide any timeline or promise that it will land for sure, but I think it will be implemented some time in the future.
