### ISSUE TITLE
`verifyOTP` throws an error on verify

### ISSUE THREAD

**Issue by ofekd** [supabase-community/supabase-flutter#251]
Said error:

```
NoSuchMethodError

NoSuchMethodError: Class '_InternalLinkedHashMap<String, dynamic>' has no instance getter 'session'.
Receiver: _LinkedHashMap len:5
Tried calling: session
```

Needless to say this completely breaks authentication. 

Offending line seems to access a nonexistent `session` field on a `Map`:

https://github.com/supabase-community/gotrue-dart/blob/c3b26dc2bcac2add53d09e7e54e0e8e06a30d7b7/lib/src/gotrue_client.dart#L287

**Comment by dshukertjr** [comment]
Thanks for opening this issue! We will fix it up ASAP!

**Comment by ofekd** [comment]
Thank you. Just FYI, it looks like some supabase queries are also typed `dynamic` and not `Map`, for example `upsert` and `insert`.

**Comment by dshukertjr** [comment]
@ofekd Do you the return value from queries like this?

```dart
final data = await supabase.from('my_table').insert(someData).selet();
```

In this case, `data` is actually expected to be dynamic, because it could return `Map`, `List` or `PostgrestResponse` when used with [count option](PostgrestResponse).

**Comment by ofekd** [comment]
Thanks for dealing with this so quickly, @dshukertjr 

I indeed was talking about something like that. Surely there must be a way to narrow the typing/split the methods to avoid the same kind of bug happening in codebases that use supabase-dart

**Comment by Vinzent03** [comment]
We are currently discussing this in #252
