### ISSUE TITLE
Unknown return type

### ISSUE THREAD

**Issue by kaboc** [supabase-community/supabase-flutter#252]
**Describe the bug**

> Missing variable type for 'data'. 
> 
> Try adding an explicit type, or remove implicit-dynamic from your analysis options file.

The Dart analyzer shows this error in both pieces of code below in an environment where `implicit-dynamics: false` is set. It is impossible to even run the app because of this error. I cannot use supabase 1.0.0 or above until it is fixed.

Code from README of the supabase package:

```dart
main() {
  final supabase = SupabaseClient('supabaseUrl', 'supabaseKey');

  // Select from table `countries` ordering by `name`
  final data = await supabase
      .from('countries')
      .select()
      .order('name', ascending: true);
}
```

Code from README of the postgrest package:

```dart
final url = 'https://example.com/postgrest/endpoint';
final client = PostgrestClient(url);
final response = await client.from('users').select();
```

**To Reproduce**

1. Enable the strong mode by adding some settings to `analysis_options.yaml`. (See the bottom of this report.)
2. Paste the code above in the editor of an IDE.
3. See the error.

**Expected behavior**

There is no error mentioned above.

**Screenshots**

![supabase_bug](https://user-images.githubusercontent.com/20254485/197334615-a4389258-0629-45c6-ba41-f12e1fd23e0b.jpg)

**Smartphone (please complete the following information):**
 - Version [e.g. 1.0.0-dev.4]
     - What do "Smartphone" and "1.0.0-dev.4" mean here? If it's about the package version, I found this bug in supabase 1.0.1.

**Additional context**

- Packages should be developed with stricter rules about types, otherwise its users will likely get into trouble.
    - e.g.
       ```yaml
       analyzer:
         strong-mode:
           implicit-casts: false
           implicit-dynamic: false
       ```
- I'm currently experiencing this error in postgrest, but I think it would be better to see if other supabase packages have the same issue and improve them if any.

**Comment by kaboc** [comment]
It looks like #186 is related.

I had searched beforehand for a similar report on supabase-dart and postgrest-dart but failed to check supabase-flutter. I apologise.

**Comment by dshukertjr** [comment]
@kaboc Thanks for opening this issue. I know we don't advertise feature enough, but we do have a `withConverter` for postgrest methods that can be used like this:

```dart
final data = await supabase
    .from('random')
    .select()
    .withConverter<List<Country>>((dynamic data) =>
                            (data as List).map(Country.fromJson).toList());
```

Would this be something similar to what you were looking for?

**Comment by kaboc** [comment]
@dshukertjr 
It'll be fine for now if it removes all errors I'm currently seeing. I'll try it out, thanks!

I don't think it solves all issues though, because if it is the only solution, it means I always have to use `withConverter`.

**Comment by Vinzent03** [comment]
I think this somewhat just moves the lint error to `withConverter`, because the parameter of the converter function is still `dynamic`.

**Comment by dshukertjr** [comment]
@kaboc What would be the ideal solution that you are looking for?

**Comment by kaboc** [comment]
@dshukertjr 
My idea is to specify all generic types explicitly. I'm thinking it'll solve the issue related to `dynamic`.

Here is a simplified version of the relevant classes.

```dart
class PostgrestBuilder<T> {}

class PostgrestClient {
  PostgrestQueryBuilder from() {
    return PostgrestQueryBuilder();
  }
}

class PostgrestQueryBuilder extends PostgrestBuilder {
  PostgrestFilterBuilder select() {
    return PostgrestFilterBuilder(this);
  }
}

class PostgrestFilterBuilder extends PostgrestTransformBuilder {
  PostgrestFilterBuilder(PostgrestBuilder builder) : super(builder);
}

class PostgrestTransformBuilder<T> extends PostgrestBuilder<T> {
  PostgrestTransformBuilder(PostgrestBuilder<T> builder);
}
```

However, I can't reproduce the error with it when I write code like below.

```dart
Future<void> main() async {
  final client = PostgrestClient();
  final data = await client.from().select(); // No error.
}
```

The cause may be somewhere else.

**Comment by Vinzent03** [comment]
I proposed something similar in #162, but it's very hard, because the type does not only depend on different methods, but also on different parameters like `count`.

How is
```dart
Future<void> main() async {
  final client = PostgrestClient();
  final data = await client.from().select(); // No error.
}
``` 
different from your code in your screenshot? Is the code in a different location, so not being affected by the lint?

**Comment by dshukertjr** [comment]
It sounds like the error will go away if we fix this? https://github.com/supabase-community/supabase-flutter/issues/186

**Comment by kaboc** [comment]
@Vinzent03 
> different from your code in your screenshot? Is the code in a different location, so not being affected by the lint?

I created a package with the simplified version without `implicit-dynamic: false`, and used it from another package with `implicit-dynamic: false`. I think I should be able to reproduce the issue, but something is wrong.

**Comment by kaboc** [comment]
@dshukertjr 
I guess so, but I'm not sure because I can't reproduce the error with the simplified version.

**Comment by kaboc** [comment]
@dshukertjr 
Oh wait! I noticed a squiggly line shown on `await`. Hovering on it shows:

> 'await' applied to 'PostgrestFilterBuilder', which is not a 'Future'.

None of `from()`, `select()` and `order()` returns Future, so the documents are wrong, right? 

```dart
final data = await supabase
    .from('countries')
    .select()
    .order('name', ascending: true);
```

```dart
final response = await client.from('users').select();
```

**Comment by kaboc** [comment]
The reason why my simplified version didn't reproduce the error was because I simplified the PostgrestBuilder class too much. It should've been `class PostgrestBuilder<T> implements Future<T?>`, not `class PostgrestBuilder<T>`.

**Comment by dshukertjr** [comment]
@Vinzent03 Yeah, the `count` option is making things hard, isn't it?

I guess the quick and dirty way of solving this problem would be to make `from` generic so that users can pass the type of the returned value.

```dart
final data = await supabase.from<List<Map<String, dynamic>>>('countries').select();
```

What I don't like about this syntax is that the js SDK had a feature similar to this that worked like this:

```typescript
// inferred type of `data` is `Country[]` if it's a normal select query
const { data, error } = await supabase.from<Country>('countries').select()

// inferred type of `data` is `Country` is a single object if it's a `single` query
const { data, error } = await supabase.from<Country>('countries').select().single()
```

But I don't know if it is possible to do this in flutter library without any breaking changes. Changing the return type on whether or not count option has been specified is the tricky part.

**Comment by dshukertjr** [comment]
I wonder if we can solve this one by updating Postgrest so that it will always return `PostgrestResponse`. By adding all the methods that exists on Map and List would have. Haven't put a whole lot of thought into it, so don't know how realistically possible it is, but just throwing it out there. Even if it was possible, it would technically be a breaking change though...

```dart
class PostgrestResponse<T> {
...
        @override
        operator [](Object? key) {
           return data[key];
        }
}

```

**Comment by kaboc** [comment]
It appears that the strong-mode rules are deprecated and the language modes should be used instead.
https://dart.dev/guides/language/analysis-options#enabling-additional-type-checks

I get no error after enabling the newer rules. I'm not sure if it's really good that I don't even see any warnings, but anyway I can use the package now.

The remaining issues are:

- Someone still using `implicit-dynamic: false` cannot use the postgrest package.
- The result of methods like `select()` and `insert()` is `dynamic`.

In the cloud_firestore package, `Object?` is returned if `withConverter()` is not used. I think it is somewhat better than `dynamic`.

**Comment by dshukertjr** [comment]
>In the cloud_firestore package, Object? is returned if withConverter() is not used. I think it is somewhat better than dynamic.

This makes sense, and seems like an easy win for us! Thanks for the suggestion!

**Comment by dshukertjr** [comment]
>In the cloud_firestore package, Object? is returned if withConverter() is not used. I think it is somewhat better than dynamic.

I was just taking a look at the cloud_firestore package, but in what case does it return `Object?`? 

In this case, res has type of `DocumentSnapshot<Map<String, dynamic>>` it seems like.
```dart
final res = await FirebaseFirestore.instance
    .collection('')
    .doc('')
    .get();```

**Comment by kaboc** [comment]
@dshukertjr 
Oops, my bad! It was just doing wrong in the declaration of a variable.

```dart
late final DocumentSnapshot doc;  // DocumentSnapshot<Object?>
try {
  doc = await _db.doc('...').get();
} on Exception catch (e, s) {
  ...
}
```

I'm sorry, the `get()` method certainly returns data of type `Map<String, dynamic>`, without the mistake above.

**Comment by kaboc** [comment]
The snapshot is not `DocumentSnapshot<T>` but `DocumentSnapshot<T extends Object?>`. It avoids `dynamic` when the generic type is omitted, so it may be a clue to the solution...?

**Comment by dshukertjr** [comment]
@kaboc Love it! Let us do that!

**Comment by dshukertjr** [comment]
Just for visibility, we ended up going with the following API

```dart
/// `T` is
/// - [List<Map<String, dynamic>>] for queries without `.single()` or `maybeSingle()`
/// - [Map<String, dynamic>] for queries with `.single()`
/// - [Map<String, dynamic>?] for queries with `.maybeSingle()`
final data = await supabase.from('users').select<T>();
```

**Comment by kaboc** [comment]
@dshukertjr 
Thanks for fixing the issue quickly! Is it necessary to specify a type when we use methods like `select()`, or is the type inferred automatically?

**Comment by Vinzent03** [comment]
Sadly you need the specify the type manually. We found no way to infer the type without a breaking change.

**Comment by kaboc** [comment]
@Vinzent03 
I'm fine with it. Thank you! I just hope others won't find it inconvenient or hate the additional breaking change right after v1...

**Comment by Vinzent03** [comment]
It's not a breaking change, because you don't have to specify the type. If not you get dynamic as before this feature.

**Comment by kaboc** [comment]
Sounds nice! Sorry, I misunderstood it.
