### ISSUE TITLE
supabase_flutter 1.0.1 signUp function throwing errors

### ISSUE THREAD

**Issue by avalanche-tm** [supabase-community/supabase-flutter#253]
I have upgraded supabase_flutter to 1.0.1 and I'm suddenly getting 'Database error finding user' when trying to signUp a user. Database is empty. Error happens only when calling signUp for the first time, each consequent call will succeed until I get another error 'Access token refresh retry limit exceded'. 

 ```dart
final testUsers = ['user1', 'user2', 'user3'];

 for (final testUser in testUsers) {
    final res = await Supabase.instance.client.auth.signUp(
      email: testUser,
      password: 'test123',
    );
  }
```

This code was working perfectly with previous version of supabase_flutter 0.3.3.

**Comment by dshukertjr** [comment]
Hi @avalanche-tm 

It seems like you are calling signUp methods for multiple users at once, but what is the use case here? `signUp` is meant to be called by the user themselves, and it is not designed to be called on behalf of another person.

**Comment by avalanche-tm** [comment]
Hi @dshukertjr 

This code is a part of program that is seeding users for testing purposes. I didn't find any other solution how to dynamically create users. Do you happen to know if there is a better way of doing this?

**Comment by dshukertjr** [comment]
@avalanche-tm 

Ah, I see! Yup, we are missing some server side methods on this library at the moment. It sounds like introducing the admin methods in this library would be the proper solution for this issue. I have opened an issue. here https://github.com/supabase-community/supabase-flutter/issues/254

Would it be okay to close this issue in favor of the 👆this one?

**Comment by Vinzent03** [comment]
Using the admin api to not persist a user session is better, but I think this code should still work and not throw any errors, right?

**Comment by avalanche-tm** [comment]
@dshukertjr unfortunately I have to agree with @Vinzent03 as this same code worked without a problem in 0.3.3. I'm looking forward to new features, but in the meantime I have to figure out how to make the old code work.

**Comment by dshukertjr** [comment]
@avalanche-tm 
I am guessing in the actual code you are using, you  have email addresses here instead of just some string?

```dart
final testUsers = ['user1', 'user2', 'user3'];
```

I just tried it with the following code and had no luck reproducing this issue. Do you run this code against a local supabase instance?

```dart
final testUsers = [
  'user1+dfsa@gmail.com',
  'user2+dfsa@gmail.com',
  'user3+dfsa@gmail.com'
];

for (final testUser in testUsers) {
  final res = await Supabase.instance.client.auth.signUp(
    email: testUser,
    password: 'test123',
  );
  print(res);
}
```

Certainly if everything worked fine, it would be great, but if there is a proper way of fixing the issue, then we should prioritize the proper fix. `signUp` is not meant to be called multiple times in a role, so supporting this use case is not exactly top priority.

**Comment by avalanche-tm** [comment]
@dshukertjr email addresses indeed, I have omitted @ part by mistake in the code I pasted, but I do have them in real code. I was testing this with local Supabase instance.

**Comment by Vinzent03** [comment]
I had the error `Database error finding user` myself a while ago. I think it was some configuration issue on the postgres part: https://github.com/supabase/supabase/issues/1479 might help.

**Comment by Vinzent03** [comment]
I just looked into a package from me, where I'm catching this error and it's commented with `the backend is not ready yet'. It's long ago I wrote that code, but I think it was when I tried to create an account just after starting the local supabase instance via cli. I don't know if that's the case for you as well.

**Comment by avalanche-tm** [comment]
> I just looked into a package from me, where I'm catching this error and it's commented with `the backend is not ready yet'. It's long ago I wrote that code, but I think it was when I tried to create an account just after starting the local supabase instance via cli. I don't know if that's the case for you as well.

I wasn't starting local instance but issuing 'supabase db reset'. If I wait a minute or so longer after getting message in terminal 'Finished supabase db reset on branch main' this error won't appear. This is still a bit awkward as well. But I still get 'Access token refresh retry limit exceded' after couple of users are created. In my e

@dshukertjr here is the updated code:

```dart
  final testUsers =
      List<String>.generate(30, (index) => 'user$index+dfsa@gmail.com');

  for (final testUser in testUsers) {
    final res = await Supabase.instance.client.auth.signUp(
      email: testUser,
      password: 'test123',
    );
    print(res);
  }

```
