### ISSUE TITLE
auth.setAuth() alternative for v1?

### ISSUE THREAD

**Issue by ahndwon** [supabase-community/supabase-flutter#255]
**Describe the bug**
Hello, I was using auth.setAuth() for custom auth from this [discussion](https://github.com/supabase/supabase/discussions/417#discussioncomment-2002384)

But it seems auth.setAuth() is removed from v1.
I'd like to know if there is an alternative.

 - Version 1.0.1

**Comment by ahndwon** [comment]
Found [migration docs](https://supabase.com/docs/reference/javascript/upgrade-guide#use-a-custom-access_token-jwt-with-supabase)

closing issue.

**Comment by nerixim** [comment]
@ahndwon 
Hi. Could you kindly share your solution?
The link you provided is for the JS client, and it's updating auth headers with custom JWT. The problem is that in Flutter you can set headers only during initialization, so how do you manage your state changes (login, logout)?

**Comment by sunilguptasg** [comment]
@nerixim - were you able to solve this? Please help. 

In fact the documentation is blank.

![Screenshot 2022-11-08_17-46-58-859](https://user-images.githubusercontent.com/93675025/200561779-1e5d38ce-b626-4258-8180-c089c1043241.png)

**Comment by nerixim** [comment]
@sunilguptasg 
Unfortunately, I couldn't find a way to do it, so I'm using v0 now.

**Comment by Vinzent03** [comment]
@dshukertjr The goal of v1.0.0 was improved dev experience, but removing `setAuth` makes things just more complicated. Is the only reason for not keeping it that gotrue-js removed it?

**Comment by omishah** [comment]
> Found [migration docs](https://supabase.com/docs/reference/javascript/upgrade-guide#use-a-custom-access_token-jwt-with-supabase)
> 
> closing issue.

It's empty !! What did you find, can't understand !!

**Comment by dshukertjr** [comment]
@nerixim @omishah @sunilguptasg 
What are the use cases? setAuth is mainly used to override the auth header for server side use. 

You can pass headers like this to override the defualt auth headers set by Supabase.
```dart
final supabase = SupabaseClient(supabaseUrl, supabaseKey, headers: {
  'Authorization': 'Bearer $access_token',
});
```

@Vinzent03 
Yup, the reason for removing it was to align the Flutter library with the js library.

**Comment by sunilguptasg** [comment]
My use case is as follows:

**Comment by sunilguptasg** [comment]
My use case is (and using with V0.x of supabase_flutter):
> SMS Auth with Firebase Auth
> A firebase function creates the Supabase JWT, and attached to the auth return 
> On auth, extract the JWT from the firebase auth
> Set the JWT using Supabase.instance.client.auth.setAuth(JWT)
> The Firebase auth token is then used for all Supabase activities, incl RLS

**Comment by sunilguptasg** [comment]
final supabase = SupabaseClient(supabaseUrl, supabaseKey, headers: {
  'Authorization': 'Bearer $access_token',
}); >> worked! Thanks @dshukertjr 

One question - do I still need to do this in main.dart:

await Supabase.initialize(
      url: SupabaseConfig.supabaseUrl,
      anonKey: SupabaseConfig.supabaseAnonKey,
    );

**Comment by nerixim** [comment]
My use case is to use an OAuth provider not yet supported by [gotrue](https://github.com/supabase/gotrue/issues/451#issuecomment-1295889997).

@dshukertjr Thank you for the solution, going to try it. Looks like I need to use some global state to set the token inside [onAuthStateChange](https://supabase.com/docs/reference/dart/auth-onauthstatechange) callback.

Maybe docs need a clarification, as the [Flutter section](https://supabase.com/docs/reference/dart/initializing#flutter-initialize) doesn't cover that.

**Comment by dshukertjr** [comment]
@sunilguptasg @nerixim 
Thanks for sharing your use cases!

@sunilguptasg 
I have updated the example code [here](https://github.com/supabase/supabase-flutter/issues/255#issuecomment-1308293775). If you are using supabase-flutter, it might be easier to just pass the header in the `Supabase.initizlize()` function. You can run the `Supabase.initialize()` anywhere in your app, as long as it is called before you make a request to Supabase!

@nerixim 
>Looks like I need to use some global state to set the token inside [onAuthStateChange](https://supabase.com/docs/reference/dart/auth-onauthstatechange) callback.

By `the token inside [onAuthStateChange]`, do you mean the access token inside the session object?
```dart
supabase.auth.onAuthStateChange.listen((data) {
  final session = data.session;
  session.accessToken; // This access token?
});
```

Yup, that sounds great! Adding this example to override the access token in the Flutter docs!

**Comment by nerixim** [comment]
@dshukertjr 
Thanks for updating your code example.
I'm new to Flutter, and I didn't know I could reinit my Supabase instance by disposing of it. I believe that fulfils my use case now, thank you 👍

**Comment by leandrorazevedo** [comment]
In my case, i need to use RLS with a value inside the JWT and **stream** with supabase_flutter.
RLS works fine, but stream does not.

if i remove the RLS, the stream works again.

**My policy :**
```
create policy "Allow only notifications to Owner's in JWT"
on notifications
for all
with check (
  (auth.jwt() ->> 'Id')::int = notifications."owner"
);
```

Basically, I use custom auth passing a JWT in the header:

```
await Supabase.initialize(
    url: 'xxxxxxx',
    anonKey: 'xxxxxxxxxx',
    headers: {
      'Authorization':
          'Bearer xxxxxxxxxx',
    },
  );
```


```
late final Stream<List<Map<String, dynamic>>> _stream;

  @override
  void initState() {
    _stream = Supabase.instance.client.from('notifications').stream(['id']);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return StreamBuilder(
      stream: _stream,
      builder: (context, snapshot) {
        return Container();
      },
    );
  }

```


RLS is working normally. But the STREAM stops working!



Can anyone help me?
