### ISSUE TITLE
Documents of postgrest is not up-to-date

### ISSUE THREAD

**Issue by kaboc** [supabase-community/supabase-flutter#256]
**Describe the bug**

From readme of postgrest-dart:

```dart
final response = await client.from('users').select();
```

From readme of supabase:

```dart
final data = await supabase
    .from('countries')
    .select()
    .order('name', ascending: true);
```

`select()` and `order()` don't return a Future, so I think `await` is wrong there.

Another sample code below also looks wrong or misleading regarding error handling.

```dart
try {
  final data = await client.from('users')
    .insert([
      {'username': 'supabot', 'status': 'ONLINE'}
    ]);
} on PostgrestException catch (error, stacktrace) {
  ...
}
```

According to the source code of the package, `insert()` returns `PostgrestFilterBuilder`, which inherits `PostgrestTransformBuilder`, which inherits `PostgrestBuilder` implementing `Future`. So the result of `insert()` is a kind of Future.

I'm guessing the inserting operation has not yet finished when `insert()` ends. If it is right, the try-catch above only catches the exception that occurs during the synchronous operation of the `insert()` method. An exception that occurs during the asynchronous operation after that has to be caught separately, but the above code does not show it. The code does not show how to wait for the insertion to complete either.

**To Reproduce**

N/A

**Expected behavior**

All documents have correct information.

**Comment by Vinzent03** [comment]
Did you change your code? `select` and all the other methods do return a future. They all return descendants of `PostgrestBuilder`, which, as you said, implement `Future`. 

I don't understand your exceptions catching problem. If you await the query, it will make the postgrest call. Why should the exception not being caught?

**Comment by kaboc** [comment]
@Vinzent03 
Ah, I got confused while I was looking into #252 using excessively simplified code without implementing Future. I'm sorry that I misunderstood `select()` and `insert()` didn't return a future.

So the document is correct. It is another issue that I get the "Missing variable type" error if I use `await` for those methods in a project with implicit dynamic disabled. I'll close this issue. Thank you.
