### ISSUE TITLE
Provider auth on all platforms

### ISSUE THREAD

**Issue by Sesa1988** [supabase-community/supabase-flutter#261]
I updated to one of the dev versions and made it work again, it was straight forward (except my other issue on windows: https://github.com/supabase-community/supabase-flutter/issues/239).
After the update to 1.0.1 no platform works except on my live version because Im still using the dart implementation and package there. Looks like my Google Oauth configuration is correct. 

I checked multiple official documentations at multiple places and I can't find the issue...

<img width="879" alt="Screenshot 2022-10-28 at 11 55 40" src="https://user-images.githubusercontent.com/26410357/198560267-a002c492-288d-4437-b976-f800665ee85d.png">

```dart
await Supabase.initialize(
    url: EnvironmentHelper.supabaseUrl,
    anonKey: EnvironmentHelper.supabaseKey,
    authCallbackUrlHostname: 'callback',
    localStorage: const CustomHiveLocalStorage(),
  );
```

```xml
<intent-filter>
      <action android:name="android.intent.action.VIEW" />
      <category android:name="android.intent.category.DEFAULT" />
      <category android:name="android.intent.category.BROWSABLE" />
      <data android:scheme="com.sesa.cryptowulf.dev" android:host="callback" />
</intent-filter>
```

```dart
@override
  Future<bool> signInWithGoogle() async {
    return await _supabaseClientService.get().auth.signInWithOAuth(
          Provider.google,
          redirectTo:
              'com.sesa.cryptowulf.${EnvironmentHelper.envName}://callback',
        );
  }
```

<img width="501" alt="Screenshot 2022-10-28 at 12 02 20" src="https://user-images.githubusercontent.com/26410357/198561365-3113ee16-a1ec-4576-b569-18fd7015ca2a.png">

It looks like everything is fine If I watch the auth logs but the redirect back does not work. The browser wants to Redirect to localhost:3000.

**Comment by dshukertjr** [comment]
@Sesa1988 
So that issue is that with the most recent version of supabase-flutter, specifying `redirectTo` does not change the redirect URL, correct?

>except on my live version because Im still using the dart implementation and package there

What version of supabase-dart are you using for this one?

**Comment by Sesa1988** [comment]
> @Sesa1988 
> So that issue is that with the most recent version of supabase-flutter, specifying `redirectTo` does not change the redirect URL, correct?
> 
> >except on my live version because Im still using the dart implementation and package there
> 
> What version of supabase-dart are you using for this one?

Its looks like it, the browser should connect to my specified URL and not localhost or?

Yes its on the latest one and I was using the latest dart package for supabase.

**Comment by dshukertjr** [comment]
@Sesa1988 
Within the project that is not working properly, could you open `pubspec.lock` and see what version of `gotrue` is being used?

**Comment by dshukertjr** [comment]
There was an issue with `gotrue` v1.0.1 with redirect. If the version you are using is not v1.0.2, could you delete your pubspec.lock file and rerun pub get?

**Comment by Vinzent03** [comment]
(Or to not update other packages, run `dart pub upgrade gotrue`. This should do the trick as well, but verify in `pubspec.lock` as Tyler said.)

**Comment by Sesa1988** [comment]
Okay thanks I will try that.

First I thought its maybe because of my forked versions for the Windows implementation at the other issue but this should not be in any relation.

I will update the other issue with my new findings.

**Comment by dshukertjr** [comment]
@Vinzent03 Thanks for sharing that trick! I keep forgetting that one 😂

@Sesa1988 
Thanks for bearing with us!

**Comment by Sesa1988** [comment]
It looks like Im already using the 1.0.2 version.

```
gotrue:
    dependency: transitive
    description:
      name: gotrue
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
```

**Comment by dshukertjr** [comment]
@Sesa1988
So sorry there. Found a bug in the code. Fixing it right now!

**Comment by Sesa1988** [comment]
> @Sesa1988
> So sorry there. Found a bug in the code. Fixing it right now!

Thanks a lot! :)

**Comment by dshukertjr** [comment]
@Sesa1988 Redirect issue should fixed now!

**Comment by Sesa1988** [comment]
> @Sesa1988 Redirect issue should fixed now!

I tested google auth and it works now on Android, iOS, and macOS.
