### ISSUE TITLE
A simple app for real-time chat

### ISSUE THREAD

**Issue by iampopal** [supabase-community/supabase-flutter#34]
A simple app for real time chat with a group of users and single users 
With caching and realtime features to well learn that supabase can help us.

**Comment by bdlukaa** [comment]
There is an official quickstart guide: https://supabase.io/docs/guides/with-flutter

**Comment by iampopal** [comment]
I have already went with this, but i need a real time chat simple apps with caching.

**Comment by dshukertjr** [comment]
Posting a recent article on how to create a simple chat application using Flutter and Supabase. It does not have any caching mechanisms though. 
https://supabase.com/blog/2022/06/30/flutter-tutorial-building-a-chat-app

**Comment by bdlukaa** [comment]
Caching is a flutter-specific thing that the dev would need to implement himself. I don't see a reason to implement cache in realtime.

Can this be closed?

**Comment by dshukertjr** [comment]
Yup, makes sense! Let's close this one!
