### ISSUE TITLE
auth.signUp not returning the data.user

### ISSUE THREAD

**Issue by nereolopez** [supabase-community/supabase-flutter#39]
# Bug report

## Describe the bug

First of all, thanks for this package. It is awesome to be able to use Supabase with Flutter!
According to the [documentation](https://supabase.io/docs/reference/dart/auth-signup), if `Email Confirmations` is enabled, the `signUp()` method should return the `user` filled in,  but `session` should be empty. Nevertheless, the reality is that the `response` object always comes with all its properties (data, error, provider, rawData and url) as `null`. 

## To Reproduce

When `Email Confirmations`is turned on, `response.data` is always null in the code below.

```dart
Future<String> _signUp(Registration registration) async {
    final response = await supabase.auth
        .signUp(registration.user.email!, registration.password!);

    if (response.error == null) {
      print('Sign up was successful for user ID: ${response.data!.user!.id}'); // DATA IS ALWAYS NULL
      return response.data!.user!.id;
    }

    print('Sign up error: ${response.error!.message}');
    return '';
  }
```

## Expected behavior

When `Email Confirmations`is turned on, `response.data` is not null and has the `user` property filled in with the newly created user. 

## Screenshots
Below is our configuration together with the code and the watch on the breakpoint. 

![image](https://user-images.githubusercontent.com/5878234/137009638-56594193-568a-4610-a126-bf187ff12753.png)
![image](https://user-images.githubusercontent.com/5878234/137010493-c16ecb61-7497-42ee-ae11-4becc2914525.png)

## System information

- OS: macOS, Windows 10
- Tested on: Chrome, iOS and Android
- Version of supabase: 
    - supabase: ^0.2.7
    - supabase_flutter: ^0.2.8

Thanks for your support!

**Comment by nereolopez** [comment]
Hi @dshukertjr !

thanks for the response. I am new to Flutter and Supabase, but was investigating a bit to see what it should be and try to raise a reasonable PR :) 

The JS library returns everything (`data`, `user`, `session` and `error`) regardless if they have value or not.
https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts#L158

In the Dart library, I saw that [there are different objects](https://github.com/supabase/gotrue-dart/blob/c217d81d88c8b7e91a48024f668155d0897c8fb5/lib/src/gotrue_response.dart) that could be returned (`GoTrueSessionResponse`, `GoTrueUserResponse`, `GoTrueJsonResponse`...) but `signUp()` is returning in all the cases the `GoTrueSessionResponse` object. 
https://github.com/supabase/gotrue-dart/blob/c217d81d88c8b7e91a48024f668155d0897c8fb5/lib/src/gotrue_api.dart#L17

So, I am wondering if following the given model it should return the `GoTrueUserResponse` object [in the case for when the email verification is required](https://github.com/supabase/gotrue-dart/blob/c217d81d88c8b7e91a48024f668155d0897c8fb5/lib/src/gotrue_api.dart#L41) instead of the `GoTrueSessionResponse` or if it should be more aligned with the JS counterpart (and the documentation) where everything is returned every time with the corresponding values in each case (so maybe `GoTrueJsonResponse`?). 

Once I understand what would be really expected or what would be your recommended implementation, if I implement the change, how could I test it locally to ensure the PR works as expected? 

Thanks!

**Comment by nereolopez** [comment]
Hi @dshukertjr! Thanksnfornthe detailed response and proposal. Now I am late on my response. I am on a business trip since last Sunday. Will try to check it mid next week once back. Thanks!

**Comment by nereolopez** [comment]
Hi @dshukertjr, sorry for my very late reply. I had more trips in between and could not take a look at it. I hope to find some time to go through it this week. 
Your code should work. I don't remember every detail. I think it would still behave a bit different than the docs, but at least should allows us to unblock the sign up on our side. As I am new to this, I will probably will spend more time on getting everything running and tested than implementing this small change, but will give it a shot and let you know if get stuck. Thx!

**Comment by dshukertjr** [comment]
@nereolopez 

I hope you are having amazing trips, and no worries at all! Whenever you have the time for it should be fine 😄 Take as much time as you would like!

Also, if in any case you don't have the band width to do it, please feel free to let us know here!

**Comment by nereolopez** [comment]
Hi @dshukertjr. We've been discussing (we are two friends on a side project) on this and other challenges we are facing and finally we've decided to move the project away from Flutter to gain more traction on the project as we are more familiar with other technologies and also the official package from Supabase is built for JS. Sorry I was not finally able to share the PR. Really appreciate all the exchange we had!

**Comment by dshukertjr** [comment]
Thanks for the update @nereolopez! No worries at all! Just out of curiosity, but will you build your project using react native, or is it a web app?

**Comment by nereolopez** [comment]
Thanks @dshukertjr. Actually we were thinking more in Angular + Capacitor :)

**Comment by vadrian89** [comment]
Hi, I am also curious about this issue as I want to implement a registration form with more data (last name, first name, etc.).

Since there is no data returned, on the registered user, there is no way of creating profiles with extra data from the registration form. Or is there?

![image](https://user-images.githubusercontent.com/8177798/148510006-ec63b7cd-2947-448a-8463-459cd22cd662.png)

**Comment by nereolopez** [comment]
Hi @vadrian89 , that is my understanding also. If you have email verification activated, that is the current behavior of the library. There are few proposals above to modify it so that you get the `auth.user` back when the sign up succeeds. Once that is done, you would have the data needed to store the additional information in your own `users` table (or whatever you call it) just by linking the user to the `auth.user.id`.
