### ISSUE TITLE
auth.signIn without email confirmation is not redirecting automatically after being authenticated

### ISSUE THREAD

**Issue by ReinetteTinekerr** [supabase-community/supabase-flutter#40]
# Bug report
auth.signIn without email confirmation does not redirect automatically after being authenticated
## Describe the bug
onAuthenticated and onUnauthenticated overrides did not detect changes after signIn/signUp. So I currently rely on 

```dart
supabase.auth.onAuthStateChange((event, session) {
      if (event == AuthChangeEvent.signedIn) {
        
      }
    });
```

to detect for auth change

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS:Windows
- Browser: chrome
- Version of supabase_flutter: 0.2.8

**Comment by bdlukaa** [comment]
See #46 and #16. Deep linking is only supported on mobile.

**Comment by tananga** [comment]
I have the same issue on IOS. I can login to google but then im stack on browser. If I click done Im redirected to App and it looks like Im authenticated. Just this automatic redirection from browser to app is not working

**Comment by CodeCakePie** [comment]
Is it planned to also support this on Windows/MacOs apps?
I would really love to see this feature :)

**Comment by dshukertjr** [comment]
@CodeCakePie Yup, we do have an issue for it [here](https://github.com/supabase-community/supabase-flutter/issues/106)!

**Comment by dshukertjr** [comment]
Closing this issue as we no longer have `onAuthenticated` and `onUnauthenticated` methods.
