### ISSUE TITLE
Cannot re-initialize Supabase

### ISSUE THREAD

**Issue by dsyrstad** [supabase-community/supabase-flutter#65]
## Steps to reproduce:

1. Call `Supabase.initialize(url, anonKey)`.
2. Later the app needs to change to a different URL (i.e., switching environments while the app is running), so it calls:
```dart
Supabase.instance.dispose();
Supabase.initialize(newUrl, newAnonKey);
```
## Actual Result:
On the second `initialize()` call, an error is thrown:
`Error: LateInitializationError: Field 'client' has already been initialized.`

## Expected Result:
I'm able to reinitialize the static Supabase singleton instance as often as needed since it's the only one I've got.

## Workaround:
I could create and manage my own `SupabaseClient` instance and just ignore `Supabase` from the `supabase_flutter` package. Note that this loses some functionality, like saving the auth state in Hive/local storage.

**Comment by bdlukaa** [comment]
Seems related to #54

**Comment by dsyrstad** [comment]
> Seems related to #54

@bdlukaa  Idk. #54 seems unrelated and vague. This issue seems like an error in null-safety conversion/handling - the `client` attribute cannot be re-assigned.
