### ISSUE TITLE
local developement in flutter not working.

### ISSUE THREAD

**Issue by growthondev** [supabase-community/supabase-flutter#69]
For some reason if I initialize the supabase with local env

```dart
const SUPABASE_URL = 'http://localhost:54321';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsI.....'
 await Supabase.initialize(
    url: SUPABASE_URL,
    anonKey: SUPABASE_KEY,
  );
```
and If I try to signup I got `Invalid authentication credentials`

I am not sure what is wrong but this was working fine with js version of supabse.

Thank you for the great project :D

**Comment by Shiba-Kar** [comment]
Facing the same issue

**Comment by dshukertjr** [comment]
@growthondev @Shiba-Kar So sorry to take some time to getting back on this issue. 

@growthondev when you tried this with js client, did you try it on a web app, or was a native app using react native?

**Comment by growthondev** [comment]
@dshukertjr @Shiba-Kar 
with js I just used web app.
Actually I figure out the reason.
since in Android emulator's "localhost"  is pointing to different ip,

`const SUPABASE_URL = 'http://127.0.0.1:54321';`
doing this will solve the problem :D

**Comment by bdlukaa** [comment]
Closing as resolved!
