### ISSUE TITLE
Feature request: Moving `jsonDecode` to separate isolate

### ISSUE THREAD

**Issue by ozum** [supabase-community/supabase-flutter#77]
Hi,

According to flutter docs, moving `jsonDecode` to a separate isolate enhances the performance: https://docs.flutter.dev/cookbook/networking/background-parsing#4-move-this-work-to-a-separate-isolate

Since `postgrest-dart` is in the critical path of supabase and is used by many components repeatedly, using isolates could increase the performance of supabase.

**Comment by bdlukaa** [comment]
I believe this is appliable to all dart libraries, not only postgrest.
