### ISSUE TITLE
Error while reconnecting: Cannot add event after closing

### ISSUE THREAD

**Issue by cgestes** [supabase-community/supabase-flutter#80]
Saw this yesterday, can't give much context, this doesn't happen often.
I looked at the code, but I am not sure the issue comes from this lib

Using realtime_client version: "0.1.15"

```
Bad state: Cannot add event after closing

Stack trace:
#0      _StreamController.add (dart:async/stream_controller.dart:595)
supabase-community/realtime-dart#1      _CompleterSink.add (package:web_socket_channel/src/sink_completer.dart:90)
supabase-community/realtime-dart#2      RealtimeClient.push.callback.<anonymous closure> (package:realtime_client/src/realtime_client.dart:215)
supabase-community/realtime-dart#3      new RealtimeClient.<anonymous closure> (package:realtime_client/src/realtime_client.dart:85)
supabase-community/realtime-dart#4      RealtimeClient.push.callback (package:realtime_client/src/realtime_client.dart:213)
supabase-community/realtime-dart#5      RealtimeClient.push (package:realtime_client/src/realtime_client.dart:226)
supabase-community/realtime-dart#6      Push.send (package:realtime_client/src/push.dart:60)
supabase-community/realtime-dart#7      Push.resend (package:realtime_client/src/push.dart:46)
supabase-community/realtime-dart#8      RealtimeSubscription.sendJoin (package:realtime_client/src/realtime_subscription.dart:189)
supabase-community/realtime-dart#9      RealtimeSubscription.rejoin (package:realtime_client/src/realtime_subscription.dart:196)
supabase-community/realtime-dart#10     RealtimeSubscription.rejoinUntilConnected (package:realtime_client/src/realtime_subscription.dart:76)
supabase-community/realtime-dart#11     new RealtimeSubscription.<anonymous closure> (package:realtime_client/src/realtime_subscription.dart:29)
supabase-community/realtime-dart#12     RetryTimer.scheduleTimeout.<anonymous closure> (package:realtime_client/src/retry_timer.dart:46)
```

**Comment by dshukertjr** [comment]
We did a major rework of the realtime-dart library recently in the developer preview version (soon to be stable release!). I wonder if you still encounter this issue with the new version.

**Comment by cgestes** [comment]
closing. will re-open if it reappears.

**Comment by ofekd** [comment]
I am seeing this after a while of inactivity. Cannot reliably reproduce

**Comment by dshukertjr** [comment]
@ofekd Do you know roughly how long? Around an hour?

**Comment by ofekd** [comment]
@dshukertjr I'd say 45-90 minutes

**Comment by ofekd** [comment]
@dshukertjr If it helps, I also get a `JWT Expired` during that period on database operations.

**Comment by ofekd** [comment]
@dshukertjr I did not

**Comment by ofekd** [comment]
@dshukertjr yes that is correct.

The project is not open source, but did stumble upon another exception, which I've forgot to copy, about reaching the limit of JWT refresh requests. Did not see it since

**Comment by dshukertjr** [comment]
@ofekd 
Hmm, interesting. Would you mind opening a support ticket from your project dashboard?

You can do so by clicking "Help" -> "Contact Support"

<img width="1426" alt="Screen Shot 2022-11-19 at 13 18 13" src="https://user-images.githubusercontent.com/18113850/202833775-00ef8f26-cffe-4a85-b9fb-092a1c53e214.png">
