### ISSUE TITLE
Latest posgres update breaks querying with or filter

### ISSUE THREAD

**Issue by brycegoh** [supabase-community/supabase-flutter#85]
# Bug report
Using supabase-dart to query a table using filters but it returns null.
Supabase team reverted the recent postgres upgrade and everything works now.

# Reproduce:
### Query table:
```dart
supaBaseClient
        .from('posts')
        .select()
        .or("blocked_ids.eq.$userId, blocked_ids.is.NULL");
```
        
### Error:
PostgrestError(message: "failed to parse logic tree ((blocked_ids.eq.6, blocked_ids.is.NULL))" (line 1, column 23), code: null, details: unexpected "n" expecting "or", hint: null)

# plugin version:
    supabase: ^0.2.8

**Comment by dshukertjr** [comment]
Sorry that I didn't notice this one and thanks for closing it. Yes, I agree with @bdlukaa on this one and we should not automatically remove spaces in between.
