### ISSUE TITLE
Array being passed as String ("[]") in realtime event

### ISSUE THREAD

**Issue by gcostaapps** [supabase-community/supabase-flutter#86]
Hi, I have an array field as one of my columns. When the realtime gets the inserted event and the array is empty my payload.newRecord contains an empty array as string ("[]") and not the array itself. I think it wasn't this way before because my code was working and now I tested and it's breaking. Using the latest version of supabase.

I don't know if it's a real issue or it'll be that way from now on.

**Comment by dshukertjr** [comment]
Seems fixed now!
