### ISSUE TITLE
PostgREST requests appear as realtime subscriptions and prevents the websocket connection from closing

### ISSUE THREAD

**Issue by osaxma** [supabase-community/supabase-flutter#89]
To observe the issue:

```dart
void main() {
  supabaseClient.from('table_1').select();
  supabaseClient.from('table_2').select();
  supabaseClient.from('table_1').select();
  supabaseClient.from('table_3').select();
  supabaseClient.from('table_4').select();

  supabaseClient.realtime.channels.forEach((element) {
    print(element.topic);
  });
}
```

This will print:
```
realtime:public:table_1
realtime:public:table_2
realtime:public:table_1
realtime:public:table_3
realtime:public:table_4
```

This is an issue because when removing the only or the last real subscription, the `websocket` connection will never close. The reason is that `openSubscriptions` will never be 0 if any PostgREST request was performed before/during a realtime subscription. 
https://github.com/supabase-community/supabase-dart/blob/2d5be1c6968da5944f8b3b039e351b38a953d815/lib/src/supabase.dart#L94-L96

I believe the root cause is here as a realtime `_subscription` is created for any query and then added to channels in the constructor of `SupabaseRealtimeClient`:

https://github.com/supabase-community/supabase-dart/blob/2d5be1c6968da5944f8b3b039e351b38a953d815/lib/src/supabase_query_builder.dart#L13-L29

I'm not sure about the reasoning behind this so I don't know what's a good fix.

**Comment by dshukertjr** [comment]
With https://github.com/supabase-community/supabase-dart/pull/122, this should be fixed!
