### ISSUE TITLE
Because supabase depends on supabase_flutter ^0.2.12 which depends on supabase ^0.2.14, supabase ^0.2.14 is required.

### ISSUE THREAD

**Issue by Coolzoheth** [supabase-community/supabase-flutter#93]
Running "flutter pub get" in supabase...                        
Because supabase depends on supabase_flutter ^0.2.12 which depends on supabase ^0.2.14, supabase ^0.2.14 is required.
So, because supabase is 1.0.0+1, version solving failed.
pub get failed (1; So, because supabase is 1.0.0+1, version solving failed.)
exit code 1

**Comment by bdlukaa** [comment]
Did you name your project `supabase`?

**Comment by Coolzoheth** [comment]
> Did you name your project `supabase`?

yes

**Comment by bdlukaa** [comment]
That's the issue! Your project can't be named `supabase`, since supabase is a dependency used by `supabase_flutter`. When running `flutter pub get`, flutter assumes the `supabase` dependency used by `supabase_flutter` is your project
