### ISSUE TITLE
Handle subscribing to the same channel on the client side. 

### ISSUE THREAD

**Issue by dshukertjr** [supabase-community/supabase-flutter#94]
This is just a passing thought, realtime has a limitation on the server side where a it can only have one connection per client per channel. 

From [relatime-js](https://github.com/supabase/realtime-js)
>Duplicate Join Subscriptions
While the client may join any number of topics on any number of channels, the client may only hold a single subscription for each unique topic at any given time. When attempting to create a duplicate subscription, the server will close the existing channel, log a warning, and spawn a new channel for the topic. The client will have their channel.onClose callbacks fired for the existing channel, and the new channel join will have its receive hooks processed as normal.

For example:
```dart
client
.from('countries')
.on(SupabaseEventTypes.all, (payload) {})
.subscribe();

client
.from('countries')
.on(SupabaseEventTypes.all, (payload) {})
.subscribe(); <- as soon as we connect the second one on `countries`, the first subscription above will disconnect
```

I wonder if we can do something fancy on the client side where when a new subscription is created, it will check if the same subscription exists, and if so, it will just serve the data from the first one. 

Having the same subscriptions on multiple locations within the app is a pretty common design pattern using Firebase, so it would be nice if we could do the same.

**Comment by dshukertjr** [comment]
Now that we can specify the topic of real-time channel, I don't know is this issue is relevant.

**Comment by Vinzent03** [comment]
As discussed in #231 we want to keep that low level control to the user.
