### ISSUE TITLE
GraphQL queries should be supported on the client

### ISSUE THREAD

**Issue by bdlukaa** [supabase-community/supabase-flutter#95]
# Context

Projects created after 28th March 2022 and self-hosted setups now can make use of GraphQL.

It supports queries over HTTP requests, for example:

```
curl -X POST https://<PROJECT_REF>.supabase.co/graphql/v1 \
    -H 'apiKey: <API_KEY>'\
    -H 'Content-Type: application/json' \
    --data-raw '
    {
      "query":"{ accountCollection(first: 3) { edges { node { id } } } }"
    }'
```

# Request

We should support this in `postgrest-dart`, with something like:

```dart
final data = await client.graphql.query('{ accountCollection(first: 3) { edges { node { id } } } }');
print(data);
```

`withConverter` should also be implemented on GraphQL queries

# Resources
- https://supabase.com/blog/2022/03/29/graphql-now-available

**Comment by rlee1990** [comment]
Any update on plans for this?

**Comment by dshukertjr** [comment]
Supabase-js has not added Graph QL support to their library, and developer can choose their favorite graph QL client to use it, so I believe we will do the same for Flutter as well!

@rlee1990 You can use libraries like [graphql_flutter](https://pub.dev/packages/graphql_flutter) to use our Graph QL! Docs can be found [here](https://supabase.github.io/pg_graphql/).

**Comment by rlee1990** [comment]
> Supabase-js has not added Graph QL support to their library, and developer can choose their favorite graph QL client to use it, so I believe we will do the same for Flutter as well!
> 
> 
> 
> @rlee1990 You can use libraries like [graphql_flutter](https://pub.dev/packages/graphql_flutter) to use our Graph QL! Docs can be found [here](https://supabase.github.io/pg_graphql/).

Thanks I was wondering if that would work I'll give it a try.
