### ISSUE TITLE
Join tables on realtime subscriptions

### ISSUE THREAD

**Issue by manuelbosi** [supabase-community/supabase-flutter#98]
Does anyone know if there's a way to join tables when using realtime subscriptions?
Actually with realtime now I can only return the listened table data, but I need to get related data from another table connected through a foreign key column
In this code "payload.newRecord" only returns the table rows with foreign key column without joined data
```dart
  void _setupInsertSubscription() async {
    subscriptions['insert'] = _client.from("sl_lists").on(SupabaseEventTypes.insert, (payload) {
      final newList = ListModel.fromJson(payload.newRecord);
      lists = [newList, ...lists];
      notifyListeners();
    }).subscribe();
  }
```

**EDIT:**
I temporarily updated the code and solved it by getting "market" data manually and seems to work because I can see updates on my data.
The only thing with the code below is that flutter returns me an "Unhandle exception"
```dart
  void _setupInsertSubscription() {
    subscriptions['insert'] =
        _client.from("sl_lists").on(SupabaseEventTypes.insert, (payload) async {
      final newList = ListModel.fromJson(payload.newRecord, false);
      final int marketId = payload.newRecord!['market_id'];
      final market = await _client
          .from('sl_markets')
          .select()
          .eq('id', marketId)
          .limit(1)
          .single()
          .execute();
      newList.market = Market.fromJson(market.data);
      lists = [newList, ...lists];
      notifyListeners();
    }).subscribe();
  }
```

This is the exception
```shell
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Concurrent modification during iteration: Instance(length:6) of '_GrowableList'.
#0      ListIterator.moveNext (dart:_internal/iterable.dart:336:7)
#1      WhereIterator.moveNext (dart:_internal/iterable.dart:438:22)
#2      Iterable.forEach (dart:core/iterable.dart:325:23)
#3      RealtimeClient.onConnMessage.<anonymous closure>
package:realtime_client/src/realtime_client.dart:266
#4      new RealtimeClient.<anonymous closure>
package:realtime_client/src/realtime_client.dart:88
#5      RealtimeClient.onConnMessage
package:realtime_client/src/realtime_client.dart:251
#6      RealtimeClient.connect.<anonymous closure>
package:realtime_client/src/realtime_client.dart:110
#7      _rootRunUnary (dart:async/zone.dart:1434:47)
#8      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)<…>
```

Any ideas on how can be fixed?

**Comment by dshukertjr** [comment]
Thanks for opening this issue. We will try to work on a fix for this `concurrent modification during iteration` bug this week. Sorry for causing inconvenience.

**Comment by VittorioParagallo** [comment]
Yes it would be awesome to get realtime joins and more filters!

**Comment by dshukertjr** [comment]
I would like to close this issue as not being able to join table for realtime updates is a limitation on our realtime servers at the moment, and the unhandled exception mentioned has been resolved. 

You could also take this to [Github Discussions](https://github.com/supabase/supabase/discussions/2615) to further discuss it with the team and the community.
